### ISSUE TITLE
"torchdata=0.4.1=py38" and Conda runtime error "glibc 2.29" not found. 

### ISSUE THREAD

**Issue by mahm1846** [pytorch/data#1005]
### 🐛 Describe the bug

I installed "torchdata=0.4.1=py38" in a Conda environment. 
When I run the code, there is an error, "glibc 2.29" not found.

Our cluster run on Centos 8.5 and only has upto "glibc 2.28" . 

Is "torchdata 0.4.1"  compatible with "glibc 2.28"?
Is there a conda build  that support gilbc 2.28?
Or, is there a workaround to make "torchdata 0.4.1" work with clusters having only "glibc 2.28" . 

### Versions

torchdata=0.4.1
py38
glibc 2.28
conda 23.1.0

**Comment by ejguan** [comment]
You might want to use `torchdata 0.5.1` or nightly releases of TorchData. This issue has been fixed in #859

Feel free to re-open the issue if it doesn't work for you
