### ISSUE TITLE
Add deep copy argument to Forker datapipe

### ISSUE THREAD

**Issue by kierkegaard13** [pytorch/data#1032]
### 🚀 The feature

The deep copy argument would cause the Forker datapipe to produce two child datapipes with deep copies of the underlying datapipe objects. In the case where your underlying data is something like List[List[str]] (the underlying List[str] is mutable in this case), the Forker class would produce two child datapipes with deep copies of the underlying list of string data. The Forker class being referenced: https://pytorch.org/data/beta/generated/torchdata.datapipes.iter.Forker.html#torchdata.datapipes.iter.Forker

### Motivation, pitch

I think the functionality of the Forker datapipe would be more intuitive if it had an option to deep copy the underlying objects of the datapipe. In the case where the objects in your datapipe are mutable, the Forker class will create two datapipes with the same underlying data which can make applying separate transformations to the two child datapipes difficult.

### Alternatives

Instead of an argument, deep copy could be the default behavior if it isn't a huge performance concern.

### Additional context

See additional discussion here: https://discuss.pytorch.org/t/whats-the-point-of-datapipe-fork-if-it-doesnt-copy-the-underlying-data/172787/4

**Comment by ejguan** [comment]
Closing as https://github.com/pytorch/pytorch/pull/96030 has been merged. Pls feel free to re-open it if you have further question.
