### ISSUE TITLE
Add a CI test to guarantee new DataPipe has online doc 

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#1047]
### 🚀 The feature

Per title

Example:
I implemented `PinMemory` and related documents in #1014, but forgot to link it in https://github.com/pytorch/data/blob/main/docs/source/torchdata.datapipes.iter.rst

So, I have to open a separate [PR](https://github.com/pytorch/data/pull/1046) to add the inline doc to our website. It would be great if we can go through both [IterDataPipe](https://github.com/pytorch/data/blob/main/docs/source/torchdata.datapipes.iter.rst) and [MapDataPipe](https://github.com/pytorch/data/blob/main/docs/source/torchdata.datapipes.map.rst) to see if there is any missing DataPipe in the doc.

If it's a CI test, we can easily block a PR being landed without adding/linking the inline doc

### Motivation, pitch

Improve UX when they can't find the online doc for our DataPipe

**Comment by SvenDS9** [comment]
Would you accept a PR for this? 
I have written a simple python script that compares the `init` files with the corresponding `rst` files

**Comment by ejguan** [comment]
Thanks! That would be awesome.
