### ISSUE TITLE
Mutating a forked element changes element value in all branches

### ISSUE THREAD

**Issue by falckt** [pytorch/data#1061]
### 🐛 Describe the bug

When using `Forker` all child pipelines receive the same object. In case this object is mutable, e.g. a dictionary, modification of the object in one branch, modifies it in all. This leads to unexpected behavior. This is related to #1032, but probably affecting a lot more pipelines as it does not involve nesting.

In the following example, only the `dict1` dictionary is (explicitly) modified, but when printing the values of both branches have changed.

```python
import torchdata.datapipes as dp


def to_dict(item):
    return {
        "value": item,
        "metadata": f"item value: {item}",
    }


def add5(value):
    return value + 5


it = dp.iter.IterableWrapper(range(5))

dict1, dict2 = it.map(to_dict).fork(2)

dict1 = dict1.map(add5, input_col="value", output_col="new_value")

for d1, d2 in dict1.zip(dict2):
    print(f"{d1 is d2}, {d1}, {d2}")
```

output

```python
True, {'value': 0, 'metadata': 'item value: 0', 'new_value': 5}, {'value': 0, 'metadata': 'item value: 0', 'new_value': 5}
True, {'value': 1, 'metadata': 'item value: 1', 'new_value': 6}, {'value': 1, 'metadata': 'item value: 1', 'new_value': 6}
True, {'value': 2, 'metadata': 'item value: 2', 'new_value': 7}, {'value': 2, 'metadata': 'item value: 2', 'new_value': 7}
True, {'value': 3, 'metadata': 'item value: 3', 'new_value': 8}, {'value': 3, 'metadata': 'item value: 3', 'new_value': 8}
True, {'value': 4, 'metadata': 'item value: 4', 'new_value': 9}, {'value': 4, 'metadata': 'item value: 4', 'new_value': 9}
```

I would expect that the `dict2` is not modified and that the `d1 is d2`  test fails.

### Versions

PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1030-aws-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz
CPU family:                      6
Model:                           106
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
Stepping:                        6
BogoMIPS:                        5799.91
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd ida arat avx512vbmi pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear flush_l1d arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       192 KiB (4 instances)
L1i cache:                       128 KiB (4 instances)
L2 cache:                        5 MiB (4 instances)
L3 cache:                        54 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy==1.0.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==1.9.2
[pip3] torch==1.13.1
[pip3] torchdata==0.5.1+59663c1
[pip3] torchmetrics==0.11.1
[pip3] torchvision==0.14.1a0+b69fce3
[conda] mkl                       2022.2.1         h84fe81f_16997    conda-forge
[conda] numpy                     1.23.5          py310h53a5b5f_0    conda-forge
[conda] pytorch                   1.13.1          cpu_py310hd11e9c7_1    conda-forge
[conda] pytorch-lightning         1.9.2              pyhd8ed1ab_0    conda-forge
[conda] torchdata                 0.5.1           py310h6e501d2_2    conda-forge
[conda] torchmetrics              0.11.1             pyhd8ed1ab_0    conda-forge
[conda] torchvision               0.14.1          cpu_py310hdfb2906_0    conda-forge

**Comment by ejguan** [comment]
I personally think it's the expected behavior of fork operation. We want to minimize the copy of objects within the pipeline. The existing solution would be creating different DataPipes rather than using fork.

Since there are multiple users asking this feature, we should decide which option is better:
- Add a deepcopy argument to make sure fork doing copy on the provided object.
- Add a new DataPipe (tentatively names it as replicate) dedicatedly to do copy.

**Comment by falckt** [comment]
For basic mutable objects, in particular dicts, a shallow copy would already eliminate a lot of pitfalls. 

To avoid excessive copying one could only do it for mutable objects. 

```python
from collections.abc import MutableMapping

if isinstance(item, MutableMapping):
    item = copy.copy(item)
```

IMHO at least the behavior should be documented, such that everyone is aware of it.

**Comment by ejguan** [comment]
> For basic mutable objects, in particular dicts, a shallow copy would already eliminate a lot of pitfalls.

It depends. If the inner object is something like integer, then yes. Otherwise, it still needs deepcopy.



> IMHO at least the behavior should be documented, such that everyone is aware of it.

Totally makes sense. The[ inline-doc](https://pytorch.org/data/beta/generated/torchdata.datapipes.iter.Forker.html?highlight=fork#torchdata.datapipes.iter.Forker) does refer to `copy` which gives users confusion. Would you love to open a PR to fix it?

**Comment by NivekT** [comment]
Note that, this issue is mostly similar #1032

**Comment by falckt** [comment]
> > IMHO at least the behavior should be documented, such that everyone is aware of it.
> 
> Totally makes sense. The[ inline-doc](https://pytorch.org/data/beta/generated/torchdata.datapipes.iter.Forker.html?highlight=fork#torchdata.datapipes.iter.Forker) does refer to `copy` which gives users confusion. Would you love to open a PR to fix it?

I can try to phrase a cautionary note and open an PR for it. Is there a general advice on how to proceed in those cases though? Then I could mention it directly. At the moment I am doing
```python
fork1, fork2 = dp.fork(2)
fork1 = fork1.map(copy.copy)
fork2 = fork2.map(copy.copy)
```
which solves the problem, but does not read very well.

How about adding a `copy_fn` to `Forker`? It can default to `None` and if needed the user can supply `copy`, `deepcopy` or even a custom copy function.

**Comment by ejguan** [comment]
> How about adding a `copy_fn` to `Forker`? It can default to `None` and if needed the user can supply `copy`, `deepcopy` or even a custom copy function.

If it's acceptable to use a `copy_fn`, you can do something like:
```py
dp = ...
fork1 = pickle.loads(pickle.dumps(dp))
fork2 = dp
```
Another option is to do a function to return DataPipe:
```py
def get_dp():
    it = dp.iter.IterableWrapper(range(5))
    dict_dp = it.map(to_dict)
    return dict_dp

fork1 = get_dp()
fork2 = get_dp()
```

**Comment by NivekT** [comment]
I was thinking that `fork` can have an additional argument `copy_element=False` or (`deep_copy=False`). If it is set to `True`, it can copy or deep copy the element before yielding it. Thoughts?

**Comment by falckt** [comment]
I created a PR for pytorch pytorch/pytorch#96030 with a potential interface and a note highlighting the behaviour. Please let me know what you think.

**Comment by sehoffmann** [comment]
Coming from a cpp background, I'm strongly opposed to making premature copies just to be safe. In my opinion, the best course of action is to highlight this behavior in the documentation and let the user decide if and **how** he wants to copy objects. Otherwise we needless incur unnecessary and potentially unwanted overhead. Adding another map that does the copying into the pipeline is trivial and also more in-line with torchdata's modular approach IMHO.

**Comment by ejguan** [comment]
@sehoffmann 

I don't disagree with you about making premature copies and another map would do the work. But, generally speaking, users expect more syntax sugar when doing python functional programming. So, we end up with `fork` no-copy by default and detailed comment if `copy` strategy is provided.
Let us know if you think the doc is not sufficient https://pytorch.org/data/main/generated/torchdata.datapipes.iter.Forker.html?highlight=fork#torchdata.datapipes.iter.Forker

**Comment by ejguan** [comment]
Closing this issue for now as https://github.com/pytorch/pytorch/pull/96030 has been merged. Pls feel free to re-open it if needed.
