### ISSUE TITLE
Profiling support

### ISSUE THREAD

**Issue by platers** [pytorch/data#1072]
### 🚀 The feature

I would like to profile my datapipes to understand which stages take the most time.

### Motivation, pitch

I have a long data pipeline that needs to be sped up. I have a custom pipe for each processing/augmentation step, and would like to know which steps are taking the most time.

### Alternatives

I can comment out some augmentation steps to see if throughput improves, but this is not possible for many steps.

**Comment by ejguan** [comment]
TorchData does have PyTorch profiler integrated. You should be able to get the profiling result for iteration speed per DataPipe
