### ISSUE TITLE
pip install torchdata

### ISSUE THREAD

**Issue by d4l3k** [pytorch/data#109]
Is the pypi package torchdata associated with this project? I naively ran `pip install torchdata` when trying to install this package and got some unexpectedly unrelated project. 

https://pypi.org/project/torchdata/

That doesn't seem to have any github sources corresponding to it so wondering what's going on with that package.

**Comment by ejguan** [comment]
> Is the pypi package torchdata associated with this project? I naively ran pip install torchdata when trying to install this package and got some unexpectedly unrelated project.

Simply speaking, we plan to upload wheel pypi in the short future. We plan to release against PyTorch 1.11.

That package is from a community repo. We have asked the writer to transfer it to us. Stay tuned for our first release. It should be held on both PyPi and conda.

**Comment by d4l3k** [comment]
@ejguan got it, thanks for the clarification! Excited to try this stuff out :)

**Comment by NivekT** [comment]
Closing this issue as our package is now on PyPI
