### ISSUE TITLE
Invalid copyright notice

### ISSUE THREAD

**Issue by sehoffmann** [pytorch/data#1125]
### 🐛 Describe the bug

https://github.com/pytorch/data/blob/main/docs/make.bat

This file is identical to the sphinx-quickstart `make.bat` file. Claiming copyright for it seems legally questionable.

### Versions

latest

**Comment by NivekT** [comment]
Good catch! Thanks for spotting it. It was likely an accident when we added the headers to lots of files and I am fixing it.

**Comment by NivekT** [comment]
Fixed by #1126
