### ISSUE TITLE
default pin_memory_fn with string Sequences and batch_size 1

### ISSUE THREAD

**Issue by Modexus** [pytorch/data#1157]
### 🐛 Describe the bug

Pinning collated batches of size 1 of strings yields the string in a list instead of the string itself.
E.g. ['hello'] -> ['h', 'e', 'l', 'l', 'o']

```python
from torchdata.datapipes.iter import IterableWrapper

dp = IterableWrapper(["hello", "world"])
dp = dp.batch(1)
dp = dp.collate()
dp = dp.pin_memory()

print(next(iter(dp)))
```
```
['h', 'e', 'l', 'l', 'o']
```

Seems to be because in the `pin_memory_fn` on line 30 `type(data)(*pinned_data)` calls list on the string itself. For batch sizes > 1 this leads to an error which just returns `pinned_data`.
Should this line be  `type(data)(pinned_data)`?

### Versions

torchdata.__version__=='0.7.0a0+cacf355'

**Comment by ejguan** [comment]
Thanks, will send a patch shortly.
