### ISSUE TITLE
iter(dataset) is called twice for certain cases of state restore of IterableDataset

### ISSUE THREAD

**Issue by gokulavasan** [pytorch/data#1267]
### 🐛 Describe the bug

Consider this code:
```
class DatasetStateIterable(torch.utils.data.IterableDataset, Stateful):
    def __init__(self, length):
        self.length = length

    def __iter__(self):
        print("Calling iter")
        return iter(list(range(self.length)))

    def state_dict(self):
        return {"key": "value"}

    def load_state_dict(self, state_dict):
        pass

class TestSimple(TestCase):
    def test(self):
        dataset = DatasetStateIterable(100)
        dl = StatefulDataLoader(
            dataset=dataset,
        )
        it = iter(dl)
        print(next(it))
        state = dl.state_dict()
        print(state)
        del dl
        print("Creating a new dl")
        dl2 = StatefulDataLoader(
            dataset=dataset,
        )
        dl2.load_state_dict(state)
        it2 = iter(dl2)
        print(next(it))
        print(dl2.state_dict())
        self.assertTrue(False)
```

The above code calls iter on the dataset twice as seen below after the state restore. The output of the above looks as follows. Note that this also happens when num_workers > 0 due to recreation here (https://github.com/pytorch/data/blob/82918dd12281e69d39fa80bfeabfc02b1f93561c/torchdata/stateful_dataloader/worker.py#L122-L134):

```
Calling iter
tensor([0])
{'_index_sampler_state': ...}
Creating a new dl
Calling iter
Calling iter
tensor([1])
{'_index_sampler_state': ...}
```

### Versions

As of commit 82918dd

**Comment by andrewkho** [comment]
Can you try this again with the t=0 diff merged? I suspect that it fixes this @gokulavasan

**Comment by gokulavasan** [comment]
@andrewkho No, it doesn't fix it. iter is called twice - https://github.com/pytorch/data/blob/a25d58c1198bb225383194fd88864f5dbaaeb6b8/torchdata/stateful_dataloader/worker.py#L131-L149, once on L131 and again on L149

**Comment by andrewkho** [comment]
ah I see, I can fix this
