### ISSUE TITLE
[WIP] Examples for demonstrating the usage and incremental value of TorchData Nodes

### ISSUE THREAD

**Issue by divyanshk** [pytorch/data#1352]
### 🚀 The feature

Starting this issue to track minimal examples we can create to demonstrate effective usage and value of TorchData nodes. I can create separate issues for each of these as required.

### Motivation, pitch

1. Vanilla torch.utils dataloader usage ported over to torchdata nodes
2. GPU accelerated transforms
3. Flexible parallelism (mixing multiprocessing with multithreading)
4. Examples porting over popular OSS datasets
    -  connecting to popular cloud storage
5. Example creating new nodes (might get covered through examples above)
6. Basic multimodal model trained E2E using torchdata nodes
7. Chaining multiple transforms (might get covered through examples above)
8. Dataset mixing (with different sampling strategies)

**Comment by andrewkho** [comment]
Discussions:
let's do 1, 2, 4 but with HF, 6 through torchtune, and 8

**Comment by andrewkho** [comment]
Also add tasks for Documentation, READMEs, docstrings, param lists, design doc

**Comment by andrewkho** [comment]
Contribution guide (lower priority)
