### ISSUE TITLE
missing/truncated docs text for torchdata.nodes

### ISSUE THREAD

**Issue by rbavery** [pytorch/data#1408]
### 📚 The doc issue

https://pytorch.org/data/main/what_is_torchdata_nodes.html#how-does-torchdata-nodes-perform

> With GIL python, torchdata.nodes with multi-threading performs better than multi-processing in some scenarios, but makes features like GPU pre-proc easier to perform which can boost

### Suggest a potential alternative/fix

not sure!

**Comment by andrewkho** [comment]
Nice catch @rbavery !

**Comment by andrewkho** [comment]
This is fixed on main now https://pytorch.org/data/main/what_is_torchdata_nodes.html#how-does-torchdata-nodes-perform Thanks @rbavery for flagging!
