### ISSUE TITLE
Multiprocessing with any DataPipe writing to local file

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#144]
### 🐛 Describe the bug

We need to take extra care all DataPipe that would write to file system when DataLoader2 triggered multiprocessing. If the file name on the local file system is same across multiple processes, it would be a racing condition.
This is found when TorchText team is using `on_disk_cache` to cache file.
DataLoader needs to know such DataPipe must be sharded with multiprocessing or enforce it into single process.

As a workaround, users have to download the file to local file system to prevent writing within DataPipe.

### Versions

main branch

**Comment by ejguan** [comment]
cc: @Nayef211

**Comment by Nayef211** [comment]
Thanks @ejguan for creating the issue. This is blocking distributed training for torchtext training recipes which uses torchdata backed dataset. I will follow the issue and hopefully we can get a fix for this soon!

**Comment by ejguan** [comment]
One option to support backward compatibility is to modify `Saver` with a mutex or wait until a process has finished writing to the file.

**Comment by Nayef211** [comment]
> One option to support backward compatibility (new DataPipe with old DataLoader) is to modify `Saver` with a mutex or wait until a process has finished writing to the file.
> 
> Edit: Then, we don't need to wait until DataLoader2 coming out.

This seems like a promising approach. Do you guys have any plans to work on this in the foreseeable future? I can also try to contribute once I have more bandwidth!

**Comment by ejguan** [comment]
> > One option to support backward compatibility (new DataPipe with old DataLoader) is to modify `Saver` with a mutex or wait until a process has finished writing to the file.
> > Edit: Then, we don't need to wait until DataLoader2 coming out.
> 
> This seems like a promising approach. Do you guys have any plans to work on this in the foreseeable future? I can also try to contribute once I have more bandwidth!

Feel free to grab it. I might not have time to add it in the next a couple of weeks.

**Comment by parmeet** [comment]
@ejguan I wonder if there is someone looking at this issue and trying to implement mutex around saver datapipe? 
cc: @hudeven

**Comment by ejguan** [comment]
Sorry that I haven't found time to work on this.

**Comment by NivekT** [comment]
> One option to support backward compatibility (new DataPipe with old DataLoader) is to modify `Saver` with a mutex or wait until a process has finished writing to the file.
> 
> Edit: Then, we don't need to wait until DataLoader2 coming out.

It seems like we need something within DataLoader to handle all these locks across writers of different DataPipes? I think wrapping a mutex around a single `Saver` will not suffice since another `Saver` may still try to access the same file for writing. Is this correct?

**Comment by parmeet** [comment]
> A `mutex` shared across processes would be sufficient in my mind. But, I don't know if there is a cross-platform solution for it.

@hudeven is looking into the solution in this diff D35459528. Basically it is using io_path's file locking mechanism which internally depends on [portalocker](https://github.com/WoLpH/portalocker). would this be a viable cross-platform solution? 

> as a work around to prevent DataLoader2 or mutex blocking the users of TorchText, could we add an extra logic in each Dataset's function to directly download the dataset to bypass `Saver` for now.

Sorry, I don't fully follow this. Since each process is instantiating and executing the dataset, I guess the problem of multiple processes writing to the same file would still be there if if we do direct download right?


cc: @NicolasHug Wondering if you are also encountering into this issue with DDP and vision datasets when multiple processes trying to write to the same cache file?

**Comment by NicolasHug** [comment]
Thanks for the ping Parmeet. I haven't encountered this issue thus far, because torchvision datasets do not write anything to disk.
