### ISSUE TITLE
Update caching examples with the latest API

### ISSUE THREAD

**Issue by NivekT** [pytorch/data#158]
### 🐛 Describe the bug

Now that the PR related to the refactoring of `on_disk_cache` is merged, we need to update the caching [examples](https://github.com/pytorch/data/tree/main/examples) to reflect the latest API.

### Versions

main branch

**Comment by ejguan** [comment]
Wait. I thought I had updated them.

**Comment by ejguan** [comment]
You are right. I didn't modify the notebook files. Send a PR later. Thanks

**Comment by ejguan** [comment]
Closing as the PR is landed.
