### ISSUE TITLE
Raise Error when HTTPReader get 503 Response

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#160]
### 🐛 Describe the bug

As I was testing the https://github.com/pytorch/data/blob/main/examples/text/CC100.ipynb, it would yield Error saying the object can not be decoded. I dug a little bit and found the root cause was HTTPResponse is a 503 Error.

But, I would expect the Error/Exception should be caught by HTTPReader
https://github.com/pytorch/pytorch/blob/2431218ee4ac1d2f016188c29869d817f6e3c70c/torch/utils/data/datapipes/iter/httpreader.py#L33-L38.

Not sure if this is related to streaming option. Needs to investigate.

### Versions

main

### Additional Context for New Contributors

See comment below

cc: @NivekT

**Comment by NivekT** [comment]
For new contributors who would like to work on this issue, we recommend: 
1. Reproduce the exception if possible
2. Implement changes that catch the error in `HTTPReader` and handle/re-raise the error as appropriate
3. Update the unit test for `HTTPReader` to ensure the new behavior works as expected

**Comment by NivekT** [comment]
@diegoaichele This has not been fixed yet. Please go ahead. Feel free to comment here if you have questions or open a PR. Thanks!
