### ISSUE TITLE
Add a different bucketbatch DataPipe with max_token_num

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#161]
### 🚀 The feature

Requested by audio domain to have a bucketbatch with `max_token_num` (maybe also with infinite buffer).

### Motivation, pitch

A DataPipe to have similar logic like https://github.com/pytorch/audio/pull/2147

`min_len` and `max_len` can be achieved by a filterDataPipe.

### Alternatives

We may be able to combine it with the existing bucketbacth. And, `max_token_num` is mutual exclusive with `batch_num`. If so, we need to take extra care about the signature of such DataPipe.

cc: @nateanl

**Comment by erip** [comment]
cc @parmeet

**Comment by erip** [comment]
I've been thinking about this and I'm interested to consider how this implementation will look. One challenge I envision is with materialization of the "lengths list" which is used to create the batches. Perhaps this is a feature that's only supported in `MapDataPipe`s unless there's some clever way to handle 1) getting lengths of all examples, 2) using the indices corresponding to those lengths to retrieve examples from the underlying data.

**Comment by ejguan** [comment]
Thanks @erip ,

I was talking to @nateanl earlier about the same concern. One of the reasons that`IterDataPipe` is introduced is to handle huge dataset that doesn't fit into memory. A streaming way to load data would be ideal. But, it means getting lengths of all examples may not be possible in all cases.
I consider a buffer size can be introduced for this DataPipe. If we set it as unlimited, we can load lengths into memory and run the bucket batch for all data. But, if the memory is limited, a partial bucket sampling maybe needed.
And, to save the memory, you may want to only load filename and path as the input data. And, after the batching, the actual data can be loaded and decoded based on the filename.

It's more like my high-level idea. It may be wrong when we get into detail.

**Comment by nateanl** [comment]
In torchaudio we have [``torchaudio.info``](https://pytorch.org/audio/stable/backend.html#info) method that reads the length of the audio without loading the whole file into memory. This could boost the speed of loading all the lengths into memory.

**Comment by erip** [comment]
I think that's probably a fine tradeoff as compared to having the entire dataset in memory and would work well under a finite-buffer implementation.

**Comment by ejguan** [comment]
Add a reference from TF: https://www.tensorflow.org/api_docs/python/tf/data/Dataset#bucket_by_sequence_length

**Comment by ejguan** [comment]
Closing as this is done by #283
