### ISSUE TITLE
Demux (fork) can not be serialized if there is a child not depleted

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#171]
### 🐛 Describe the bug

As shown in https://github.com/pytorch/vision/pull/5187#issuecomment-1015479165

Not just special use case like vision. If users use `in_memory_cache` or any data structure to capture/store the data from any ChildDataPipe from `demux` or `fork`, the pipeline becomes non-serializable from the second epoch.

This may not interfere the DataLoader iteration. But, it is definitely going to block snapshotting.

cc: @NivekT Do you plan to work on this?

### Versions

PyTorch core master

**Comment by NivekT** [comment]
Yes, I am aware. I believe any DataPipes that contain a buffer will not be serializable without custom `__getstate__` and `__setstate__` methods that avoid storing any components that are not serializable (e.g. the buffer).

If I understand correctly, this is not blocking anything in torchvision, correct?

**Comment by ejguan** [comment]
> If I understand correctly, this is not blocking anything in torchvision, correct?

TorchVision is actually blocked by this. They can't use demux if DataLoader is involved. The another workaround Phillip proposed would also not work. We have to fix it.

**Comment by ejguan** [comment]
> Yes, I am aware. I believe any DataPipes that contain a buffer will not be serializable without custom __getstate__ and __setstate__ methods that avoid storing any components that are not serializable (e.g. the buffer).

If `buffer` is attached to instance, serialization won't work. If `buffer` is created within iterator, then it's fine.

**Comment by ejguan** [comment]
I have no idea why I created such issue, as I have sent a PR to fix it. https://github.com/pytorch/pytorch/pull/71311
Closing. Sorry about that @NivekT

**Comment by ejguan** [comment]
Actually `Fork` is not fixed...
