### ISSUE TITLE
Add a flatmap datapipe

### ISSUE THREAD

**Issue by erip** [pytorch/data#178]
### 🚀 The feature

Add a `FlatMapDataPipe` which simulataneously flattens nested `IterDataPipe`s and applies a function to nested pipes.

### Motivation, pitch

I have tarballs containing tarballs. When dealing with these types of recursive data, it's useful to have a mechanism to both flatten the structure and apply a function to it so I only need to consider the "inner-most" data.

### Alternatives

Domain libraries can define their own impls.

### Additional context

Migrating torchtext to datapipes via torchdata would benefit from this feature when dealing with [IWSLT data](https://github.com/pytorch/text/blob/main/torchtext/datasets/iwslt2016.py#L231-L241).

**Comment by erip** [comment]
Maybe another good analog would be `flatten` which does that same thing without the intermediate `map` (equivalent, flatmap with identity function)

**Comment by ejguan** [comment]
We do have a plan to add `flatmap` but the behavior may be different than the proposal. We expect `flatmap` would expand the returned list from `map_fn`.
```py
>>> def fn(data):
...     return [data, data*10]


>>> dp = IterableWrapper([0,1,2,3])
>>> dp = dp.flatmap(fn)
>>> list(dp)
[0, 0, 1, 10, 2, 20, 3, 30]
```

We do have a operator named `unbatch`, which behaves same as `flatten`

**Comment by erip** [comment]
Hmm, I think maybe you're right and that my implementation is a `concatmap`. The difference is when the `map` happens (before for `flatmap`, after for `concatmap`). 🤔

**Comment by ejguan** [comment]
Technical speaking, this `flatmap` can also be applied in your use case. The function becomes a generator yielding data..

**Comment by erip** [comment]
Yes, the pseudocode I have in mind is basically

```python
# [ 1.tgz, 2.tgz, ..., n.tgz]
inner_tars = outer_tar.read_from_tar()

# [ 1_1.txt, 1_2.txt, 3_1.txt, 3_2.txt, 5_1.txt, ...]
inner_inner_files = inner_tars.flatmap(lambda inner_tar: FileOpener(inner_tar).read_from_tar())
```

So the `read_from_tar` becomes the generator yielding data and `flatmap` flattens it into a `IterableDataPipe`.
