### ISSUE TITLE
Implement `UnzipperIterDataPipe`

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#184]
### 🚀 The feature

Add `unzip` as requested by both Vision and Text teams.
```py
dp = IterableWrapper([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
dp0, dp1, dp2 = dp.unzip()

list(dp0)  # [1, 4, 7]
```
We may be able to reuse the logic of `_ChildDataPipe`https://github.com/pytorch/pytorch/blob/fa38e93fe98bfcbdb11288ecfbe5af5c264aabb3/torch/utils/data/datapipes/iter/combining.py#L145

Support `tuple`, `list` maybe `dict`?

### Motivation, pitch

It's way better than letting users to use the following script to mimic unzip
```py
dp = IterableWrapper([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
def expand_fn(data):
    index_data = []
    for i, d in enumerate(data):
        index_data.append((i, d))
    return index_data

dp = dp.flatmap(expand_fn)

def classify(data):
    return data[0]

dp0, dp1, dp2 = dp.demux(classify)

...
```

### Additional context

Note: We need to take extra care for these `demux`, `fork`, and future `unzip`.
If users do `dp0, dp1, _ = dp.unzip()`, this pipeline may be unserializable after iteration as the third output DataPipe is never executed.

**Comment by ejguan** [comment]
cc: @NivekT Do you want to work on it since `demux` and `fork` are both implemented by you?

**Comment by erip** [comment]
> If users do `dp0, dp1, _ = dp.unzip()`

Does it make sense to add a `ignore_idx: Union[int, Tuple[int, ...]` which allows `unzip` to skip over certain elements within the inner dp? This avoids the problem, so you'd have something like 

    dp0, dp1 = dp.unzip(ignore_idx=2) # or dp.unzip(ignore_idx=(2,))

**Comment by ejguan** [comment]
> > If users do `dp0, dp1, _ = dp.unzip()`
> 
> Does it make sense to add a `ignore_idx: Union[int, Tuple[int, ...]]` which allows `unzip` to skip over certain elements within the inner dp? This avoids the problem, so you'd have something like
> 
> ```
> dp0, dp1 = dp.unzip(ignore_idx=2) # or dp.unzip(ignore_idx=(2,)), dp.unzip(ignore_idx=(-1,)), ... 
> ```

Yeah. Probably doable.

**Comment by NivekT** [comment]
> cc: @NivekT Do you want to work on it since `demux` and `fork` are both implemented by you?

I will add it to my list of TODOs.
