### ISSUE TITLE
Support `keep_key` in `Grouper`?

### ISSUE THREAD

**Issue by pmeier** [pytorch/data#256]
`IterKeyZipper` has an option to keep the key that was zipped on:

https://github.com/pytorch/data/blob/2cf1f208e76301f3e013b7569df0d75275f1aaee/torchdata/datapipes/iter/util/combining.py#L53

Is this something we want to support going forward? If yes, it would be nice to have this also on `Grouper` and possibly other similar datapipes. That would come in handy in situations if the key is used multiple times for example if we have a `IterKeyZipper` after an `Grouper`.

### Additional Context for New Contributors

See comment below

**Comment by ejguan** [comment]
Sounds reasonable to me

**Comment by NivekT** [comment]
For new contributors who would like to work on this issue, we recommend:
1. Look at how `keep_key` is used by `IterKeyZipper`
2. Add the same feature to `Grouper`
3. Update the unit test for `Grouper` to ensure the new behavior works and is backward compatible with existing usages

**Comment by NicolasHug** [comment]
I took a quick look at this issue.
I wonder if it would make sense to instead avoid the overlap between `keep_key` and `merge_fn`? For example we could remove the `keep_key` parameter, and instead let the `merge_fn` function accept `key, source_dp_item, ref_dp_item` ? Then passing `keep_key=True` would be equivalent to passing

```
merge_fn = lambda key, source_dp_item, ref_dp_item: (key, source_dp_item, ref_dp_item)
```

**Comment by pmeier** [comment]
Yes, we should be consistent. But there is no harm to phase out `keep_key` on the datapipes that have that param in favor of `merge_fn`.

**Comment by NicolasHug** [comment]
>  @NicolasHug was your comment focused on IterKeyZipper?

Yes :)

> what is your proposal for Grouper?

That was actually going to be my next question: if we were to add a `merge_fn`, what would it look like? I guess it has to have the following signature (and default behaviour)?

```py
def merge_fn(key, *args):
    return tuple(*args)
```

**Comment by NivekT** [comment]
@NicolasHug 

If we choose to add `merge_fn` for `Grouper`, it will replace `wrapper_class`. 

https://github.com/pytorch/pytorch/blob/ea44645c9a682a4e212e64b94a86383c3388ed6b/torch/utils/data/datapipes/iter/grouping.py#L262-L264

As @ejguan mentioned, `wrapper_class` is applied onto a `List` (variable `result_to_yield`) with length not known in advance. I do agree that `Grouper` is doing something different from the `Zipper`s and such that divergence in their APIs make sense.

My proposal would be to add `keep_key` to `Grouper`, which will return a tuple `(key, wrapper_class(result_to_yield))` when `True`, and `wrapper_class(result_to_yield)` when `False`.

**Comment by NicolasHug** [comment]
Should we just add `keep_key` to `Grouper` and remove `merge_fn` from the `Zipper` then? Both APIs would be consistent.

Perhaps I'm missing something but it looks like `merge_fn` isn't really necessary since it can be achieved just as easily with a subsequent call to `Mapper`?

**Comment by ejguan** [comment]
> Perhaps I'm missing something but it looks like `merge_fn` isn't really necessary since it can be achieved just as easily with a subsequent call to `Mapper`?

Yeah. When `IterKeyZipper` starts to support multiple datapipes, the `merge_fn` is not really useful. IIRC, `merge_fn` is used as a syntax sugar for a sequence of `IterKeyZipper`.

**Comment by SvenDS9** [comment]
Is this issue still relevant? The `Grouper` class seems to be gone (or moved away?). Removing the `merge_fn` from `IterKeyZipper` is still possible. But does it still make sense? I'm looking for a good first issue :)

@ejguan

**Comment by ejguan** [comment]
@SvenDS9 Thanks for taking interest in contributing TorchData. `Grouper` is currently landed in PyTorch core: https://github.com/pytorch/pytorch/blob/ce50a8de7535b5e359f7ed7ead4285414a966d3f/torch/utils/data/datapipes/iter/grouping.py#L202-L203
So, adding a `keep_key` would be a good first issue

**Comment by SvenDS9** [comment]
Should I still work on removing the `merge_fn` from `IterKeyZipper`?

Since `Grouper` has been moved away to PyTorch core, how can I still contribute here?

On a more general note: Why has `Grouper` beend moved? Why are some DataPipes in the PyTorch Core while others are not? What is the idea behind this split?

**Comment by ejguan** [comment]
> Should I still work on removing the `merge_fn` from `IterKeyZipper`?

I think it needs to be done with this issue https://github.com/pytorch/data/issues/334

> Since `Grouper` has been moved away to PyTorch core, how can I still contribute here?

You can open a PR against PyTorch Core. And, we will review it for sure.
