### ISSUE TITLE
Extend `FSSpecFileLister` and `IoPathFileLister` to support loading multiple directories

### ISSUE THREAD

**Issue by NivekT** [pytorch/data#282]
### 🚀 The feature

**This is a good first issue for new contributors.**

Previously, `FileLister` only allowed a single directory as input argument (`root: str`). Later, in the following PR, we have added support for multiple directories (`root: Union[str, Sequence[str], IterDataPipe]`):
* https://github.com/pytorch/pytorch/pull/72260

We would like to do the same for `FSSpecFileLister` and `IoPathFileLister` if possible.

https://github.com/pytorch/data/blob/39e48da2a8a076f4a00715f82f761b606ba416f1/torchdata/datapipes/iter/load/fsspec.py#L31-L49

https://github.com/pytorch/data/blob/39e48da2a8a076f4a00715f82f761b606ba416f1/torchdata/datapipes/iter/load/iopath.py#L37-L62

Progress:
- [ ] Implement, test, and land changes for `FSSpecFileLister`
- [ ] Implement, test, and land changes for `IoPathFileLister`

### Motivation, pitch

The need to list the content of multiple directories is a common use case, and accepting multiple directories as input arguments can save users from having to write additional code to have the desired behavior.

### Alternatives

If for some reason this is not compatible for `fsspec` or `iopath`, we should reconsider.

### Additional context

To contributors, feel free to implement the change for one DataPipe (and leave the other for someone else).

After implementing the functional change, please write/update unit tests for the corresponding DataPipes. Please test the feature against an online/remote file system (e.g. Amazon S3) if possible.

cc: @VitalyFedyunin @ejguan

**Comment by ykabusalah** [comment]
@NivekT Could I tackle this issue? And if so, would you mind assigning it to me?

**Comment by NivekT** [comment]
> @NivekT Could I tackle this issue? And if so, would you mind assigning it to me?

Sure go for it.
