### ISSUE TITLE
Add TorchArrow Nightly CI Test

### ISSUE THREAD

**Issue by NivekT** [pytorch/data#301]
### 🚀 The feature

TorchArrow nightly build is now [available for Linux](https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html) (other versions will be next).

We should add TorchArrow nightly CI tests for these [TorchArrow dataframe related unit tests](https://github.com/pytorch/data/blob/main/test/test_dataframe.py).

### Motivation, pitch

This will ensure that our usages remain compatible with TA's APIs.

### Additional context
This is a good first issue for people who want to understand how our CI works. Other [domain CI tests](https://github.com/pytorch/data/blob/main/.github/workflows/domain_ci.yml) (for Vision, Text) can serve as examples on how to set this up.

**Comment by lezwon** [comment]
@NivekT I'd like to take up this issue
