### ISSUE TITLE
DataPipe for GCS (Google Cloud Storage)

### ISSUE THREAD

**Issue by NivekT** [pytorch/data#303]
### 🚀 The feature

Build a DataPipe that allows users to connect to GCS (Google Cloud Storage). There is a chance that existing DataPipes may suffice, so we should examine the relevant APIs first.

### Motivation, pitch

GCS (Google Cloud Storage) is one of the commonly used cloud storage for storing data.

### Alternatives

Existing DataPipes are sufficient and we should provide an example of how that can be done instead.

### Additional context

Feel free to react or leave a comment if this feature is important for you or for any other suggestion.

**Comment by SvenDS9** [comment]
This can be closed as we have an example: https://pytorch.org/data/beta/dp_tutorial.html#accessing-google-cloud-storage-gcs-with-fsspec-datapipes
