### ISSUE TITLE
Add tfrecord support

### ISSUE THREAD

**Issue by jkulhanek** [pytorch/data#306]
### 🚀 The feature

Please add tfrecord support. This could be implemented as a "TFRecordLoader" similar to "TarArchiveLoader". It would load the tfrecord file and parse the records.

### Motivation, pitch

A lot of TensorFlow users have their datasets stored as tfrecords for efficient data loading. It would be great to support tfrecords to be able to use the same data format for both frameworks. This would make it easier to transfer TensorFlow models to PyTorch ecosystem and vice versa.

### Alternatives

There is the following project: https://github.com/vahidk/tfrecord which works great. It would be great, however, if we allow something similar with the new data API.

**Comment by NivekT** [comment]
This seems like a reasonable request to me and we will definitely consider a PR from the community to add this. 

We'll also update here if we decide to work on it. If anyone thinks this will be valuable to their work, feel free to react or comment on this issue.

**Comment by jkulhanek** [comment]
I will provide a PR soon.

**Comment by jkulhanek** [comment]
I added a PR implementing the feature.
