### ISSUE TITLE
Add Support for bzip2 decompression in Decompressor

### ISSUE THREAD

**Issue by lezwon** [pytorch/data#309]
### 🚀 The feature

As of now [Decompressor](https://github.com/pytorch/data/blob/main/torchdata/datapipes/iter/util/decompressor.py) does not have support for .bz2 files. This could be added.

### Motivation, pitch

I am currently working on https://github.com/pytorch/vision/issues/5352 with the [USPS](https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/multiclass.html#usps) dataset which uses bzip2. I had to use bz2 directly. Would've liked to use Decompressor.

**Comment by NivekT** [comment]
Thanks for the suggestion. We will be open to accepting a PR that adds bzip2 to Decompressor.

**Comment by lezwon** [comment]
@NivekT I can take it up :)
