### ISSUE TITLE
Combining multiple `datapipes`  together

### ISSUE THREAD

**Issue by ninginthecloud** [pytorch/data#346]
### 🚀 The feature

Introduce a few more multiplexer to handle combining multiple (two or more) DataPipes. 
In this issue, I'm going to discuss 3 different multiplexers

## InOrderMultiplexer
Introduce `InOrderMultiplexerDataPipe`
Which takes a `List` of IterDataPipe, and yields items from DataPipes with respect to the order of DataPipes.

For example
```
        >>> from torchdata.datapipes.iter import IterableWrapper, InOrderMultiplexer
        >>> source_dp1 = IterableWrapper([1, 2, 3, 4])
        >>> source_dp2 = IterableWrapper([5, 6, 7, 8])
        >>> source_dp3 = IterableWrapper([9, 10])
        >>> d = [source_dp1, source_dp3, source_dp2]
        >>> inorder_mul_dp = InOrderMultiplexer(pipes_in_order=d)
        >>> list(inorder_mul_dp)
        [1, 2, 3, 4, 9, 10, 5, 6, 7, 8]
```

## ZipMultiplexer
Introduce `ZipMultiplexerDataPipe`
Which takes a `List` of IterDataPipe, and yields a dict containing batches from all DataPipes.

For example
```
        >>> from torchdata.datapipes.iter import IterableWrapper, ZipMultiplexer
        >>> source_dp1 = IterableWrapper([1, 2, 3, 4])
        >>> source_dp2 = IterableWrapper([5, 6, 7, 8])
        >>> source_dp3 = IterableWrapper([9, 10])
        >>> d = [source_dp1, source_dp2, source_dp3]
        >>> smallest_mul_dp = ZipMultiplexer(pipes_list=d, stop_condition="smallest_datast_exhausted")
        >>> list(smallest_mul_dp)
        [{'source_dp1':1, 'source_dp2': 5, 'source_dp3':9},
         {'source_dp1':2, 'source_dp2': 6, 'source_dp3':10}]
        >>> all_mul_dp = ZipMultiplexer(pipes_list=d, stop_condition="all_datast_exhausted")
        >>> list(all_mul_dp)
        [{'source_dp1':1, 'source_dp2': 5, 'source_dp3':9},
         {'source_dp1':2, 'source_dp2': 6, 'source_dp3':10},
         {'source_dp1':3, 'source_dp2': 7},
         {'source_dp1':4, 'source_dp2': 8}]
```

## RoundRobinMultiplexer
Introduce `RoundRobinMultiplexerDataPipe`
Which takes a `List` of IterDataPipe, and yields items by cycling over the DataPipes one by one.
For example
```
        >>> from torchdata.datapipes.iter import IterableWrapper, RoundRobinMultiplexer
        >>> source_dp1 = IterableWrapper([1, 2, 3, 4])
        >>> source_dp2 = IterableWrapper([5, 6, 7, 8])
        >>> source_dp3 = IterableWrapper([9, 10])
        >>> d = [source_dp1, source_dp3, source_dp2]
        >>> smallest_mul_dp = RoundRobinMultiplexer(pipes_in_order=d, stop_condition="smallest_datast_exhausted")
        >>> list(smallest_mul_dp)
        [1, 9, 5, 2, 10, 6]
        >>> all_mul_dp = RoundRobinMultiplexer(pipes_in_order=d, stop_condition="all_datast_exhausted")
        >>> list(all_mul_dp)
        [1, 9, 5, 2, 10, 6, 3, 7, 4, 8]

```

### Motivation, pitch

Combining multiple datapipes (or datasets/dataloaders) is very common in practice. 

For `InOrderMultiplexer`, user may want to validate their trained model with multiple datasets to get the evaluation on each datasets. Each dataset can be formed as one datapipe, and combining them in order could help user easily conduct validation in one round. 

For  `ZipMultiplexer`. when working on multi-task training, each datapipe represents one task. User wants a batch containing data from all datapipes. 

For `RoundRobinMultiplexer`, similar to `InOrderMultiplexer`. 

### Alternatives

Currently, torch data provide `IterKeyZipper `, but it only accepts two datapipes. There's an open issue to track this effort #334

**Comment by ejguan** [comment]
- For `InOrderMultiplexerDataPipe`, we have `concat`  in PyTorch Core serves the same behavior.
https://github.com/pytorch/pytorch/blob/4fb7fa081e4fb5df3bf7bc85dcb9a3a9a3ac7133/torch/utils/data/datapipes/iter/combining.py#L14-L30
- For `RoundRobinMultiplexer `, we do have `mux` in PyTorch Core serves the same behavior.
https://github.com/pytorch/pytorch/blob/4fb7fa081e4fb5df3bf7bc85dcb9a3a9a3ac7133/torch/utils/data/datapipes/iter/combining.py#L375-L390
- For `ZipMultiplexer`, we have `zip` in PyTorch Core serves the same behavior.
https://github.com/pytorch/pytorch/blob/4fb7fa081e4fb5df3bf7bc85dcb9a3a9a3ac7133/torch/utils/data/datapipes/iter/combining.py#L419-L433
But `zip` won't handle the case of `all_datast_exhausted`. Instead using a same op with different argument, I would like to provide `zip_longest` to handle the case of `all_datast_exhausted` to mimic the general python itertools operation https://docs.python.org/3/library/itertools.html#itertools.zip_longest

**Comment by ninginthecloud** [comment]
Thanks @ejguan for replying and pointing me all the useful code pointers~ 
> For InOrderMultiplexerDataPipe, we have concat in PyTorch Core serves the same behavior.
That's cool~ I think it serves the usage~
> For RoundRobinMultiplexer , we do have mux in PyTorch Core serves the same behavior.
`mux` implemented `all_dataset_exhausted` situation, do we consider providing `mux_shortest` to exhaust smallest dataset? 
> For ZipMultiplexer, we have zip in PyTorch Core serves the same behavior.
Similar to `mux`, `zip` handles the case of `shortest_dataset_exhausted`, we can consider `zip_longest` as well.

**Comment by ejguan** [comment]
> `mux` implemented `all_dataset_exhausted` situation, do we consider providing `mux_shortest` to exhaust smallest dataset?

This is a good question. Considering `mux` and `zip` at the same time, should we provide a unified behavior  for them? Let `mux` and `zip` representing the `shortest` and `mux_longest` and `zip_longest` for all depleted.

cc: @NivekT WDYT

**Comment by NivekT** [comment]
> This is a good question. Considering `mux` and `zip` at the same time, should we provide a unified behavior for them? Let `mux` and `zip` representing the `shortest` and `mux_longest` and `zip_longest` for all depleted.

The change to the behavior of `mux` will be BC-breaking but I do agree that this is the better API and we should switch to that.

**Comment by ninginthecloud** [comment]
> @ninginthecloud Do you want to work on this?

Yep. I will follow up with a PR.

**Comment by ejguan** [comment]
Thank you!!!
