### ISSUE TITLE
Follow up on AWSSDK integration for nightly release

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#349]
### 🚀 The feature

Adding this issue to track all follow-up works need to be done for TorchData nightly release integrated with AWSSDK for @ydaiming and myself @ejguan 

- [x] Add pybind to third-party library (submodule)
- [x] Add awssdk to third-party library (submodule)
- [x] Modify cmakelist to statically link awssdk into torchdata and validate the CI
- [ ] Convert codegen into cmake to prevent hardcoding pyi file https://github.com/pytorch/data/blob/main/torchdata/_torchdata/__init__.pyi (An stub file is needed)
- [ ] Update License before nightly release (May need to modify the release workflow by appending AWSSDK license to TorchData)
- [ ] Update nightly/official release workflow

### Motivation, pitch

The ultimate goal is to make sure AWSSDK is integrated with TorchData by default in all types of releases.

**Comment by ydaiming** [comment]
@ejguan Surely, I can work on it this week. Will discuss with you during the process.
