### ISSUE TITLE
Add validation between `input_col` and `fn` for Callable DataPipes

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#362]
### 🚀 The feature

Using `inspect` to validate the `input_col` matching `fn` input for `Mapper`, `Flatmapper` and other DataPipe using both `input_col` and `fn` as the arguments.
- [`Mapper`](https://github.com/pytorch/pytorch/blob/6dc71461e11122494a303214a72b12adb353dc4d/torch/utils/data/datapipes/iter/callable.py#L55-L57)
- [`Filter`](https://github.com/pytorch/pytorch/blob/ec591087fb95525b430f2bbcdd023567e2fb1cc9/torch/utils/data/datapipes/iter/selecting.py#L13-L47)
- [`Flatmap`](https://github.com/pytorch/data/blob/732307a1dcea8686bff9a855bcd67c32d2087f8e/torchdata/datapipes/iter/transform/callable.py#L93-L123)
- [`BatchMap`](https://github.com/pytorch/data/blob/732307a1dcea8686bff9a855bcd67c32d2087f8e/torchdata/datapipes/iter/transform/callable.py#L15-L59)
- etc

### Motivation, pitch

This would help users to identify the wrong arguments at the construction time for such `IterDataPipe` rather than at iteration time.

**Comment by davidegavio** [comment]
I'd like to work on this if possible

**Comment by xiurobert** [comment]
Was this ever worked on?

**Comment by ejguan** [comment]
Hi @davidegavio, do you still have plan to work on this issue?

**Comment by xiurobert** [comment]
I'll give this a try when I get home

**Comment by xiurobert** [comment]
@ejguan just to check, is this to check that fn has type annotations for returning a Sequence?

**Comment by ejguan** [comment]
If the provided `fn` has type annotations, we should validate the number of function's arguments matches `input_col`.

Let's say there is only 1 argument in `fn`, but `input_col` is specified as 1. We should raise Error.

**Comment by xiurobert** [comment]
What does `input_col` refer to in this scenario? Is it the dimension?

**Comment by ejguan** [comment]
Yeah. Let's say you have a DataPipe yielding tuples like `(1, 2), (3, 4), ...`.
```py
dp = IterableWrapper([(1, 2), (3, 4), ...])
dp = dp.map(lambda x: x + 1, input_col=1)
```
And, `input_col` would specify which element in each tuple should be applied by the `fn`. In this case, as `input_col=1`, the function will apply to `2, 4, ...`.

We should add inline doc to explain the behavior of `input_col`

**Comment by xiurobert** [comment]
Alright, I will work on this and open a PR.
