### ISSUE TITLE
Clean up `buffer` inside DataPipe instance during destruction

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#370]
### 🚀 The feature

Could we add `__del__` to clean up `buffer`, which are attached to `DataPipe` instance.
- Demux
- Fork
- etc

### Motivation, pitch

We may encounter the problem that the objects inside `buffer` are not clean up by `DataPipe` instance itself but relied on `gc` to clean up.
This could potentially to resolve the problem from https://github.com/pytorch/vision/pull/5801#issuecomment-1097475490

TorchVision chose to ignore the `ResourceWarning` for the test suite. But, we still need to consider for other domains or users who want to keep these warnings.

cc: @NivekT

**Comment by NivekT** [comment]
I can submit a PR for this. I gave this some thoughts, I think calling `clear()` should clear the buffer without deleting the underlying objects so that if there are other references to those objects, they will still work properly.

**Comment by NivekT** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/76345
