### ISSUE TITLE
CONTRIBUTING.md new datapipe expectations

### ISSUE THREAD

**Issue by msaroufim** [pytorch/data#376]
### 📚 The doc issue

When a new user is adding a data pipe that should work well with the rest of the pytorch/data ecosystem, we don't make it clear what users need to do like a checklist for example

1. Does your data pipe contain state
2. Is your data pipe listed in https://github.com/pytorch/data/blob/main/docs/source/torchdata.datapipes.iter.rst
3. Is your data pipe serializable https://github.com/pytorch/data/blob/6da391e3d342248a6005c74c61499a3209bda010/test/test_serialization.py to work with checkpoints
4. Do your tests assume binary data on disk? Can you generate them on the fly with a script instead
5. Anything else?

### Suggest a potential alternative/fix

Go through a new data pipe exercise and document gaps in `CONTRIBUTING.md`

cc @NivekT

**Comment by NivekT** [comment]
Hi @msaroufim, have you looked at [this section of CONTRIBUTING.md](https://github.com/pytorch/data/blob/main/CONTRIBUTING.md#adding-a-new-datapipe)?

**Comment by NivekT** [comment]
@msaroufim I do see some small gaps in that section, I will be adding a few more detailed sentences to it soon to make sure the contribution process is smooth. Thanks for raising the issue!
