### ISSUE TITLE
Add functional API to FileLister

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#387]
### 🚀 The feature

Another follow up on https://github.com/pytorch/data/pull/383

Since `FileLister` support `IterDataPipe` as input, we could provide functional API to it.

```py
dp = IterableWrapper([file_path_1, file_path_2, ...]).list_file()...
```
- FileLister: https://github.com/pytorch/pytorch/blob/d21154b0989c7baa058428a5d22f7b379147fec0/torch/utils/data/datapipes/iter/filelister.py#L10
- IoPathFileLister and FSSpecFileLister: https://github.com/pytorch/data/tree/main/torchdata/datapipes/iter/load

### Motivation, pitch

Better syntax

**Comment by xiurobert** [comment]
Hi, I know this issue is kind of old by now, but just want to check if anyone is working on this? If not, I would love to give it a try.

**Comment by ejguan** [comment]
@xiurobert 

Please go for it.

**Comment by xiurobert** [comment]
Thanks for the update. The FileLister is in the main pytorch repo, should I be contributing to that instead?

**Comment by xiurobert** [comment]
This should be implemented on IoPathFileLister and FSSpecFileLister?

**Comment by ejguan** [comment]
> This should be implemented on IoPathFileLister and FSSpecFileLister?

You can start from there.

We have another one in PyTorch Core. https://github.com/pytorch/pytorch/blob/b447114873e5febbd93d6e2bd8f18c2e72ee9caf/torch/utils/data/datapipes/iter/filelister.py#L10

**Comment by ejguan** [comment]
Yes, you are right.

**Comment by xiurobert** [comment]
Thanks. Will get hacking ASAP.
