### ISSUE TITLE
Allow users to provide `auth` and other data to `HttpReader`

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#391]
### 🚀 The feature

This should extend the functionality of `HttpReader` to send more complicated POST request.
For authentication, users don't necessarily need to provide via `http://user:password@domain.com/`. They should be able to provide `auth` to the `HttpReader` and relay it to `request`.

https://github.com/pytorch/data/blob/8b95954ce431ade5905448ebd9a2909e30566377/torchdata/datapipes/iter/load/online.py#L38-L43

### Motivation, pitch

Versatile `HttpReader`

**Comment by NivekT** [comment]
I feel that this may be a good first issue. @ejguan - feel free to remove if it may be too complicated.

**Comment by msaroufim** [comment]
I'll take a stab at this tomorrow 

Seems like there's 2 obvious ways of doing this

Here: https://github.com/pytorch/data/blob/8b95954ce431ade5905448ebd9a2909e30566377/torchdata/datapipes/iter/load/online.py#L38-L43

1. `requests.Session()` has an `auth` parameter which takes an authentication tuple
2. `request.get()` can take in a dict with all query parameters including auth

Then here https://github.com/pytorch/data/blob/8b95954ce431ade5905448ebd9a2909e30566377/torchdata/datapipes/iter/load/online.py#L186 

And then need to instead have a datapipe like `source_datapipe: IterDataPipe[Tuple[str, Optional[Dict[str,str]]]]`

And finally update docs

**Comment by ejguan** [comment]
If we only consider the use case of authentication, IMHO, providing this dict object as the input of `IterDataPipe` constructor should be sufficient as it's hard to imagine people will change username and password per url.

Based on the doc from `urllib3` (used by `requests` module), there are so many things can be supplied to  `get` function. https://urllib3.readthedocs.io/en/latest/reference/urllib3.request.html
We might add `**kwargs` to the constructor as well to relay it to https://github.com/psf/requests/blob/40956723f27daf5e0d9759208ca69cef236ab339/requests/sessions.py#L591-L600

And, for the type of `source_datapipe`, if the input data is a tuple with size 2, we can also override the `**kwargs` using the `Dict`.
