### ISSUE TITLE
TorchText tests failed when multiprocessing

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#397]
### 🐛 Describe the bug

I think the test from TorchText starts failing after https://github.com/pytorch/pytorch/pull/74984 is landed into core and shipped into nightly.

Should we either revert the change or fix this problem ASAP considering the closing branch cut for TorchText?
We can let TorchText team to remove all lambda function in their dataset if needed.

### Versions

main

### Progress
- [x] Replacing lambda usages in TorchText
         https://github.com/pytorch/text/pull/1718
- [ ] Add ability to use `dill` in DataLoaderV1
       https://github.com/pytorch/pytorch/pull/77288
- [ ] Add ability to use `dill` in DataLoaderV2 (TODO)

**Comment by ejguan** [comment]
See the domain tests in my PR https://github.com/pytorch/data/pull/394/checks

**Comment by VitalyFedyunin** [comment]
Thank you for reporting, lets fix it forward in DataLoader1 and DataLoader2

**Comment by VitalyFedyunin** [comment]
@NivekT totally makes sense to update torchtext. As parallel topic: Should we consider `dill` as hard dependency for torchdata?

**Comment by NicolasHug** [comment]
If that helps, we have opened https://github.com/pytorch/vision/pull/5938 so that you can check whether recent changes break the torchvision datapipes when `dill` is installed.

Re torchtext's useof `lambdas`: I noticed @parmeet yesterday that the use of `lambda`s will break users' code when doing multi-processing on Windows, so I believe they are planning on fixing this (would need Parmeet's confirmation though).

Regarding making `dill` a hard-dependency: doesn't `dill` silently replace `pickle` automatically?

**Comment by ejguan** [comment]
> Regarding making dill a hard-dependency: doesn't dill silently replace pickle automatically?

Yeah but technically, we can revert the change by doing `dill.extend(use_dill=False)`. https://github.com/pytorch/pytorch/blob/50efa3a6e8ff8a29f7a0cb08cf3e3e5ed42f38fe/torch/utils/data/_utils/serialization.py#L5-L15

**Comment by NicolasHug** [comment]
Do I understand correctly that this `revert ` will only affect `torchdata` code? I.e. installing `dill` will still silently replace pickle in the rest of the users environement?

**Comment by ejguan** [comment]
Install won't affect. It only affects the `pickle` when `import dill`. So, I think always reverting the change every time that`torchdata` finishes using `dill` should remove impact for other part of code.

**Comment by NivekT** [comment]
Updating the original post to track progress

**Comment by NivekT** [comment]
Keeping this open since we need the change for DataLoader V2 as well
