### ISSUE TITLE
Make requirements.txt as the single source of truth for TorchData dependencies

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#410]
### 🚀 The feature

Currently, we have two locations containing TorchData requirements:
- https://github.com/pytorch/data/blob/main/requirements.txt
- https://github.com/pytorch/data/blob/3c7769682b5263acd889c7e7f0187323f7d9e9da/setup.py#L108-L112
We can let `setup.py` to decode `requirements.txt` to generate requirements automatically.

### Motivation, pitch

It will be safer and easy to maintain.

**Comment by tal66** [comment]
Hi, I'll do this. PR soon
