### ISSUE TITLE
import fails on Linux due to missing library libcrypto.so.10

### ISSUE THREAD

**Issue by pmeier** [pytorch/data#418]
`torchvision` is seeing [CI failures](https://github.com/pytorch/vision/runs/6484672163) on Linux for a missing extension loaded by `torchdata`. I can reproduce with `docker`:

```shell
docker run python:3.7 bash -c \
    'pip install --pre torch torchdata --extra-index-url https://download.pytorch.org/whl/nightly/cpu && python -c "import torchdata"'
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/torchdata/__init__.py", line 7, in <module>
    from torchdata import _extension  # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/torchdata/_extension.py", line 34, in <module>
    _init_extension()
  File "/usr/local/lib/python3.7/site-packages/torchdata/_extension.py", line 31, in _init_extension
    from torchdata import _torchdata as _torchdata
ImportError: libcrypto.so.10: cannot open shared object file: No such file or directory
```

#399 might be the offender. #415 did not make it into yesterday's nightly.

**Comment by NicolasHug** [comment]
I think @ejguan  is on it https://github.com/pytorch/text/pull/1729#issuecomment-1128886947

**Comment by pmeier** [comment]
I think I found the issue: the Linux wheel build is running in a specific container 

https://github.com/pytorch/data/blob/f80d07b0670ca2c68f06e4dfe236a6dbe6dd1b28/.github/workflows/_build_test_upload.yml#L55

which has a different version of `libcrypto` than ubuntu:

```shell
$ docker run quay.io/pypa/manylinux2014_x86_64 bash -c 'ls -l /usr/lib64 | grep libcrypto'
lrwxrwxrwx  1 root root      19 Apr 18 12:29 libcrypto.so.10 -> libcrypto.so.1.0.2k
-rwxr-xr-x  1 root root 2520920 Mar 28 15:42 libcrypto.so.1.0.2k
```

```shell
$ docker run ubuntu:22.04 bash -c 'ls -l /usr/lib/x86_64-linux-gnu | grep libcrypto'
-rw-r--r--  1 root root 4447536 Mar 16 08:35 libcrypto.so.3
```

I was unable to install `libcrypto.so.10` on Ubuntu through vanilla `apt`. 

Thus, if we depend on this specific version, we probably need to ship it with wheel.

**Comment by ejguan** [comment]
@pmeier Thanks for reporting this. I will take a deeper look.

**Comment by ejguan** [comment]
I think `openssl-static` in https://github.com/pytorch/data/blob/f80d07b0670ca2c68f06e4dfe236a6dbe6dd1b28/.github/workflows/_build_test_upload.yml#L92 is culprit. Let me give it a try.

**Comment by pmeier** [comment]
> I think openssl-static in [...] is culprit

Nope. As you can see above, `libcrypto.so.10` is already present in the vanilla image without installing anything else.

```shell
$ docker run -it quay.io/pypa/manylinux2014_x86_64 bash
$ ls -l /usr/lib64 | grep libcrypto
lrwxrwxrwx  1 root root      19 Apr 18 12:29 libcrypto.so.10 -> libcrypto.so.1.0.2k
-rwxr-xr-x  1 root root 2520920 Mar 28 15:42 libcrypto.so.1.0.2k
$ yum -y install openssl-devel openssl-static curl-devel zlib-devel
[...]
$ ls -l /usr/lib64 | grep libcrypto
-rw-r--r--  1 root root 4697014 Mar 28 15:42 libcrypto.a
lrwxrwxrwx  1 root root      19 May 18 13:57 libcrypto.so -> libcrypto.so.1.0.2k
lrwxrwxrwx  1 root root      19 Apr 18 12:29 libcrypto.so.10 -> libcrypto.so.1.0.2k
-rwxr-xr-x  1 root root 2520920 Mar 28 15:42 libcrypto.so.1.0.2k

```

**Comment by datumbox** [comment]
@ejguan Thanks for looking into this. 

The specific issue is currently breaking TorchVision's CI for new PRs, which can cause some confusion to contributors. As Philip clarified, the issue only appears on Linux. Do you have any idea on when the fix will land? Do you recommend us to turn off the test until this is done? Thanks!

**Comment by pmeier** [comment]
The problem is that the AWS package pulls in `libcrypto`, but we don't statically link against it. Thus, when trying to import the package it looks for `libcrypto.so.10` on the system and errors out if it doesn't find that. 

If we want to depend on the compiled AWS package, we need ship `libcrypto` as well. Note that this of course has some license implications. Furthermore, this is only needed for wheels, since on conda we can simply depend on another package to provides `libcrypto`.

Looking at the CMakeLists.txt of the AWS package, `libcrypto` is mentioned two times:

- https://github.com/aws/aws-sdk-cpp/blob/c1df81935a08232b853e2d7eae6fd8c70f99d459/CMakeLists.txt#L51
- https://github.com/aws/aws-sdk-cpp/blob/c1df81935a08232b853e2d7eae6fd8c70f99d459/CMakeLists.txt#L191

**Comment by datumbox** [comment]
@ejguan Thanks for the update. Can you provide a very rough estimate on when you believe this will become available? We are trying to figure out if we should disable the specific CI job or leave it be. A rough estimate will help us decide this easier.

**Comment by ejguan** [comment]
All nightly should be updated https://github.com/pytorch/data/actions/runs/2353439246

**Comment by datumbox** [comment]
@ejguan Thanks a lot for the help. As far as I can tell, this [fixed](https://github.com/pytorch/vision/runs/6514403512?check_suite_focus=true) the problem. If no additional action is required on your side, I think we can close the issue.

**Comment by ejguan** [comment]
> @ejguan Thanks a lot for the help. As far as I can tell, this [fixed](https://github.com/pytorch/vision/runs/6514403512?check_suite_focus=true) the problem. If no additional action is required on your side, I think we can close the issue.

@datumbox 
Thank you for confirmation. Let's keep this issue opened until I fix AWS binary.

**Comment by ejguan** [comment]
Closing this issue as #421 has landed.
