### ISSUE TITLE
Magic function `reset` should not be called after __setstate__

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/data#419]
The first construction of `__iter__` after `__setstate__` should not call `reset`. 

Might be some edge cases when we restore to the state of 'no active iterator'.

>>That's a good call. I think we should do that across all DataPipes that have a custom `reset()` method.

_Originally posted by @NivekT in https://github.com/pytorch/pytorch/pull/77741#discussion_r876157282_

**Comment by NivekT** [comment]
I am adding a PR now

**Comment by NivekT** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/77774
