### ISSUE TITLE
The developer install instruction are outdated

### ISSUE THREAD

**Issue by pmeier** [pytorch/data#432]
https://github.com/pytorch/data/blob/6a8415b1ced33e5653f7a38c93f767ac8e1c7e79/CONTRIBUTING.md?plain=1#L49-L56

While debugging #418 it took my quite a while to figure out that I need to set 

https://github.com/pytorch/data/blob/6a8415b1ced33e5653f7a38c93f767ac8e1c7e79/tools/setup_helpers/extension.py#L41

for the C++ code to be built.

**Comment by ejguan** [comment]
Yeah. Closing this issue as the fix has landed.
