### ISSUE TITLE
HashChecker example is broken

### ISSUE THREAD

**Issue by pmeier** [pytorch/data#433]
https://github.com/pytorch/data/blob/6a8415b1ced33e5653f7a38c93f767ac8e1c7e79/torchdata/datapipes/iter/util/hashchecker.py#L36-L48

Running this will raise a `StopIteration`. The reason is simple: we want to read from a stream that was already exhausted by the hash checking. The docstring tells us that much

https://github.com/pytorch/data/blob/6a8415b1ced33e5653f7a38c93f767ac8e1c7e79/torchdata/datapipes/iter/util/hashchecker.py#L32-L33

and we correctly set `rewind=False`.

**Comment by NivekT** [comment]
Thanks for flagging this. We definitely need to review the examples and tutorial before the next release.
