### ISSUE TITLE
Issue during import of portalocker on windows

### ISSUE THREAD

**Issue by parmeet** [pytorch/data#441]
### 🐛 Describe the bug

Currently [TorchText CI is broken on windows](https://app.circleci.com/pipelines/github/pytorch/text/5580/workflows/4838fa07-1ae7-4087-9490-d8e35fb160fd/jobs/188952/parallel-runs/0/steps/0-108) due to following error:

```
ImportError: DLL load failed while importing win32file: The specified module could not be found
```

The error occurred during import of portalocker.

cc: @vitaly-fedyunin  

### Versions

Latest from main

**Comment by ejguan** [comment]
I haven't seen such Error in TorchData CI. The tests running on the latest main branch: https://github.com/pytorch/data/actions/runs/2359941609

Could this part be the problem? https://github.com/WoLpH/portalocker/blob/00cffcb1831208691d3bf6850df4768989a0bd4c/setup.py#L133
If circle CI windows machines are too old to be upgraded to `pywin32`, this might be the problem.

**Comment by parmeet** [comment]
Ahh I see! Thanks @ejguan for providing additional context. I am not too familiar with the CI machines on windows. I wonder if @atalman, @mthrok you provide some suggestions here?

**Comment by mthrok** [comment]
Couple of observations from quick skim
1. pywin32 is not a dependency of domains libraries, so it kinda explains why.
2. Probably not related, but the binary distributions of PyTorch core and domain libraries are, IIUC, compiled with VS 2019, while TorchData seems to be compiled with VS 2020.

The point 1. suggests that torchtext has to add pywin32 as hard dependency as well. Was this reviewed somewhere?

**Comment by ejguan** [comment]
> 1. pywin32 is not a dependency of domains libraries, so it kinda explains why.

It's weird to me because `portalocker` is introduced in TorchData however we don't see any failure on CI related to `portalocker`.


> Was this reviewed somewhere?

If you mean the PR introducing `portalocker`, it's here https://github.com/pytorch/data/pull/409

**Comment by mthrok** [comment]
> @mthrok Thanks for digging into this.
> 
> > 1. pywin32 is not a dependency of domains libraries, so it kinda explains why.
> 
> It's weird to me because `portalocker` is introduced in TorchData however we don't see any failure on CI related to `portalocker`.
> 

In #409 I do not see a change in CI or packaging script. For the downstream projects, who consume torchdata's binary distribution, the additional dependency should be written probably in `setup.py`.

> > Was this reviewed somewhere?
> 
> If you mean the PR introducing `portalocker`, it's here #409

I meant the decision /  impact of adding a dependency reviewed? TorchData being upstream of domain libraries have to be careful adding a new dependency as the number of downstream projects are large. And when it's done, it has to be done properly, so that it is transparent, and won't create a conflict with major downstream projects.

**Comment by parmeet** [comment]
> 1. pywin32 is not a dependency of domains libraries, so it kinda explains why.

Thanks @mthrok  for the investigation. To test the hypothesis, I added the dependency for testing, but seems the error persist. https://app.circleci.com/pipelines/github/pytorch/text/5584/workflows/003de168-e3ed-4941-be1a-3017aba3b446/jobs/189114

> The point 1. suggests that torchtext has to add pywin32 as hard dependency as well. Was this reviewed somewhere?

If pywin32 is indeed the issue, I would expect the dependency to be added for TorchData, not downstream libraries right?

**Comment by ejguan** [comment]
> To test the hypothesis, I added the dependency for testing, but seems the error persist. https://app.circleci.com/pipelines/github/pytorch/text/5584/workflows/003de168-e3ed-4941-be1a-3017aba3b446/jobs/189114

I do see `pywin32` with the right version installed. And, it's installed based on the dependency graph where `torchdata` depends on `portalocker`, and `portalocker` depends on `pywin32`.

**Comment by ejguan** [comment]
I have seen the same issue by searching on the website: https://lifesaver.codes/answer/dll-load-failed-while-importing-win32file-the-specified-module-could-not-be-found-17986

**Comment by ejguan** [comment]
@parmeet 
When you have time, could you please try to test if this is going to work by running `python3 .\env\Scripts\pywin32_postinstall.py -install` before testing?
I think you can download this file from https://github.com/mhammond/pywin32/blob/main/pywin32_postinstall.py

**Comment by ejguan** [comment]
> > @parmeet When you have time, could you please try to test if this is going to work by running `python3 .\env\Scripts\pywin32_postinstall.py -install` before testing? I think you can download this file from https://github.com/mhammond/pywin32/blob/main/pywin32_postinstall.py
> 
> @ejguan how do you suggest doing this testing/debugging if we don't have access to a windows system?

Could you modify CircleCi yml?

**Comment by ejguan** [comment]
Even if we are able to fix such Error using this script above, TorchData needs to add notes for users who might encounter the same problem on Windows OS.

**Comment by mthrok** [comment]
How about making it optional dependencies? I think dependency-related issues make it difficult to adopt torchdata. We were looking to adopt dataloader2, but if Windows users require such unusual step to just import the package, we are reluctant to adopt torchdata.
