### ISSUE TITLE
Upstream vision helper DataPipe

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#46]
Vision Team found a series required DataPipe to revamp the Dataset, some of them are general-purpose in https://github.com/pytorch/vision/blob/main/torchvision/prototype/datasets/utils/_internal.py

**Comment by NivekT** [comment]
I had a look at the different custom DataPipes in that file.
1. SequenceIterator
    - Perhaps we can have a flatten-er IterDataPipe? It will come with an option for the user to define how many `nesting_level` of iterable to flatten (starting from the top)? It would be somewhat similar to how `mapper` determines the level to which apply the function. Thoughts?
2. MappingIterator
    - Similar to SequenceIterator but applies to `Dict` instead. Again we flatten multiple levels of `Dict`, but it may be less relevant for this use case? Maybe this one should just unpack one level.
3. Enumerator
   - Seems straight forward and useful.
4. Decompressor
   - A single DataPipe that can detect the type of compression and act accordingly seems useful.
   - However, it may need to account for differences in the behaviors of the resulting streams (or maybe leave that handled further downstream by another DataPipe?).

**Comment by ejguan** [comment]
I agree with `Enumerator` and `Decompressor` can be upstreamed.

Just wondering does `unbatch` work similar as `SequenceIterator`?

**Comment by NivekT** [comment]
Closing this since `Decompressor` and `Enumerator` have landed.

We can re-open this issue if there is strong demand to upstream the other two DataPipes.
