### ISSUE TITLE
fsspec requires to delegate `kwargs` to FileSystem to list/load file correctly

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#494]
### 🐛 Describe the bug

Based on the current [implementation](https://github.com/pytorch/data/blob/6f1f81db751d28e675728ab36007be05db0614af/torchdata/datapipes/iter/load/fsspec.py#L69), the following code will raise `ConnectTimeoutError`.
```py
>>> import fsspec

>>> url = "s3://ai2-public-datasets/charades"
>>> fs, path = fsspec.core.url_to_fs(root)
>>> fs.ls(path)
botocore.exceptions.ConnectTimeoutError
```

However, if we provide extra arguments to `url_to_fs`, we should be able to successfully execute the following code:
 ```py
>>> import fsspec

>>> url = "s3://ai2-public-datasets/charades"
>>> fs, path = fsspec.core.url_to_fs(root, anon=True)  # The main difference here
>>> fs.ls(path)
[...]
```

It should be easily fixed by delegating extra key-word argument to all `FSSpecDataPipe`s.

### Versions

main branch

**Comment by NivekT** [comment]
This issue raised in the forum is also somewhat related:

https://discuss.pytorch.org/t/using-a-google-cloud-storage-bucket-for-dataset/146253/6?u=nivek

**Comment by ejguan** [comment]
> This issue raised in the forum is also somewhat related:
> 
> https://discuss.pytorch.org/t/using-a-google-cloud-storage-bucket-for-dataset/146253/6?u=nivek

Yeah. Will send a patch shortly. I need it to test performance of S3
