### ISSUE TITLE
Consider `isort` as linter

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/data#5]
Some of `__init__.py` imports are getting out of control, we should consider using https://pycqa.github.io/isort/ as hard linter and/or suggestion.

**Comment by pmeier** [comment]
We recently opted to use [`ufmt`](https://ufmt.omnilib.dev/en/stable/) as code formatter. It combines [`black`](https://black.readthedocs.io/en/stable/) and [`usort`](https://usort.readthedocs.io/en/stable). AFAIK, `isort` had some issues on FB architecture. cc @NicolasHug 

The [final vote is still out](https://github.com/pytorch/vision/pull/4384), but if we go for it, I can send a PR adopting it here too.

**Comment by NicolasHug** [comment]
Yes, `ufmt` was specifically made to match fb's internal `arc lint`.
If we expect pytorch/data to be modified from withing fbcode from time to time, I think it's much safe to keep fbcode linting and github linting in sync

**Comment by ejguan** [comment]
Thanks to @pmeier , we have added pre-commit hook to run auto formatter. `ufmt` is also included to make everything sorted.
Closing this Issue.
