### ISSUE TITLE
Multiprocessing and batching / collation

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/data#530]
It looks like collation works differently depending on whether `MultiProcessingReadingService` is used. Perhaps I am not using this  properly?

```py
import torchdata
from torchdata.dataloader2 import DataLoader2, MultiProcessingReadingService


dp = torchdata.datapipes.iter.IterableWrapper(range(40))
dp = dp.batch(10)
dp = dp.collate()

dl = DataLoader2(dp)
print(list(dl))
# Gives
# [tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), tensor([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]), tensor([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])]
# as expected



rs = MultiProcessingReadingService(num_workers=4)
dp = dp.sharding_filter()
dl = DataLoader2(dp, reading_service=rs)
print(list(dl))
# Gives
# [tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]), tensor([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]), tensor([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])]
# Notice the double brackets `[[ ... ]]

**Comment by NicolasHug** [comment]
This is probably related to the default `collate_fn` of the `DataLoader` in the reading service?

https://github.com/pytorch/data/blob/8682f6e09d6facc9d6105c59c9966058c182065e/torchdata/dataloader2/reading_service.py#L119-L130

This is unlikely to be a reasonable fix, but passing `collate_fn=lambda x:x[0]` will lead to consistent results.

**Comment by ejguan** [comment]
> This is unlikely to be a reasonable fix, but passing `collate_fn=lambda x:x[0]` will lead to consistent results.

It would be better when `MultiProcessingReadingService` should a special `collate_fn` to detect the type of output. If it's a single tensor, `collate_fn` should directly return it. Otherwise, like a list of Tensors, we should call default `collate_fn`.



> I think this should be addressed once `MultiProcessingReadingService` stop using the old `DataLoader`.

That would be ideal. And, I think @NivekT your snapshotting for MP also requires some modifications on `MPReadingService`. Removing `DataLoader` might reduce the amount of work (unclear to me for now)

**Comment by VitalyFedyunin** [comment]
https://github.com/pytorch/data/pull/531 fixing it
