### ISSUE TITLE
[RFC] Wrapper/Proxy for Stream

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#55]
## 🚀 Feature
Discussed with @NivekT about the wrapper class for all streams:
Pros:
- We can add a `__del__` method to close the file stream automatically when ref count becomes 0 for wrapper. It would eliminate all warnings.
- A wrapper class can unify the reading API for file streams. (For `OnDiskCache`, I would prefer a unified API to read stream, otherwise I have to handle all different cases)
  - Local file stream, we can use `read()` to read everything into memory
  - When we set `stream=True` for large file, the `requests.Response` doesn't support `read`. It only supports `iter_content` or `__iter__` to read chunk by chunk.

Cons:
- Thanks to @NivekT, it needs extra care about magic methods.

Reference: https://github.com/pytorch/data/pull/35#discussion_r728201731, https://github.com/pytorch/data/pull/65#discussion_r730117933

cc: @VitalyFedyunin

**Comment by NivekT** [comment]
> @NivekT
> 
> IIUC, `HTTPRespond` and `GDriveRespond` should also be wrapped by `StreamWrapper`

Yea, I believe they should, and they should still work as intended given that `StreamWrapper` delegates the method to the underlying object.
