### ISSUE TITLE
[TODO]  There is current a bug in TorchArrow/Velox related to conversion of arrow arrys to DataFrame that causes

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/data#595]
This issue is generated from the TODO line
https://github.com/pytorch/data/blob/2f29adba451e1b87f1c0c654557d9dd98673fdd8/./examples/criteo_torcharrow/criteo_parquet.py#L17

**Comment by NivekT** [comment]
@wenleix I don't think this is true anymore right?

If so, I can remove the TODO and close this issue
