### ISSUE TITLE
[TODO]  To be extra tidy, this should only track the execute bit

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/data#601]
This issue is generated from the TODO line
https://github.com/pytorch/data/blob/2f29adba451e1b87f1c0c654557d9dd98673fdd8/./third_party/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-lc/util/bot/extract.py#L161
cc @davidben

**Comment by NivekT** [comment]
This code is from third-party and I don't think we can change this.

cc: @ejguan

**Comment by VitalyFedyunin** [comment]
Yes, excluded, but this issue was generated before I did it.
