### ISSUE TITLE
[TODO]  Should be one of 'fork', 'spawn'

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/data#613]
This issue is generated from the TODO line
https://github.com/pytorch/data/blob/2f29adba451e1b87f1c0c654557d9dd98673fdd8/./torchdata/dataloader2/reading_service.py#L135
cc @VitalyFedyunin

**Comment by DongyuXu77** [comment]
Is anyone working on it? I could take it if it isn't

**Comment by SvenDS9** [comment]
This can probably be closed as the TO-DO does not exist anymore.

**Comment by ejguan** [comment]
@SvenDS9 Thank you, you are right.

Closing this issue as it's been fixed.
