### ISSUE TITLE
Update out-of-date example and colab

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#647]
### 📚 The doc issue

The examples for Text/Vision/Audio are out-of-date: https://github.com/pytorch/data/tree/main/examples
The colab attached in README needs to be updated as well:
- How to install torchdata
- Example needs shuffle + sharding_filter

### Suggest a potential alternative/fix

None

**Comment by ejguan** [comment]
cc: @VitalyFedyunin @NivekT since I am not sure who has the permission to edit the colab file

**Comment by VitalyFedyunin** [comment]
Sorry, which colab you are talking about?

**Comment by ejguan** [comment]
The one in here: https://github.com/pytorch/data#colab

**Comment by ejguan** [comment]
@NivekT Could you please change the colab link to the new one?

**Comment by ejguan** [comment]
Closing as the PR has been merged
