### ISSUE TITLE
DataLoader2 with OSS datasets/datapipes

### ISSUE THREAD

**Issue by dahsh** [pytorch/data#655]
For user dev and onboarding experience of the data component, we will provide examples, tutorials, up-to-date documentations as well as the operational support. We added a simple train loop example. This is to further track adding the uscase and example of DataLoader2 with open source datasets/datapipes.

**Comment by NivekT** [comment]
Closing this as documentation has been added. If additional content is needed, please comment on #763.

**Comment by dahsh** [comment]
Yeah, this makes sense. Thanks. We can also refer to the train loop under examples folder.
