### ISSUE TITLE
Check if this typecast IO causing entire object to be read into the buffer

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/data#657]
https://github.com/pytorch/data/blob/25cc03c055acfb342bfbf2065460aaf4edb1142d/torchdata/datapipes/iter/load/s3io.py#L125

CC @ejguan

**Comment by ejguan** [comment]
Using the same script from https://github.com/pytorch/data/issues/500 to test the performance w/ or w/o `BytesIO` from `S3FileLoader`.
- With `BytesIO`
```
S3FileLoader: Mean(23.807878967700006), STD(3.3510862470041345)
FSSpecFileOpener: Mean(0.0046190930000022945), STD(0.00078826165197471)
```
- Without `BytesIO`
```
S3FileLoader: Mean(23.779200960799987), STD(3.4376357340338624)
FSSpecFileOpener: Mean(0.004564887000009321), STD(0.0003228209598197885)
```
It seems the performance is on parity. So, closing the issue for now unless more investigation on typecast is required.
