### ISSUE TITLE
DataPipe with multiple possible sources

### ISSUE THREAD

**Issue by adamjstewart** [pytorch/data#672]
### 🚀 The feature

Datasets may come from many sources. For example, a dataset may be present on disk, or it may be streamed from a remote API. We would like to be able to define a single dataset that optionally reads from disk or streams from an API.

### Motivation, pitch

One of the complexities we face in [TorchGeo](https://github.com/microsoft/torchgeo) is with uncurated satellite imagery datasets. These datasets can be manually downloaded from sites like [USGS EarthExplorer](https://earthexplorer.usgs.gov/) and stored locally on disk. However, these datasets can be very large (TBs to PBs), and are already widely available in the cloud ([Azure](https://planetarycomputer.microsoft.com/catalog), [AWS](https://aws.amazon.com/earth/), [GEE](https://developers.google.com/earth-engine/datasets)). What we would like is to be able to define a single dataset that can read locally from disk, or access data from APIs on Azure, AWS, GEE, etc. Is this possible with TorchData, or is it a feature you are interested in supporting?

### Alternatives

The alternative is to make separate datasets for the cross product of `{Landsat, Sentinel, NAIP, etc.}` and `{Disk, Azure, AWS, GEE, etc.}`. However, these datasets will share many common features (both satellite-specific metadata and API-specific code). We would like to avoid code duplication if possible and make the library simple with only a single dataset per satellite.

### Additional context

Thanks for making such an awesome library! @pmeier I see you already added a pipe for extracting RAR files, that saves me time since multiple of our datasets read from RAR and [torchvision decided not to support it](https://github.com/pytorch/vision/pull/4098).

[TorchGeo](https://github.com/microsoft/torchgeo) is **strongly** considering converting all of our datasets to use TorchData. I love the idea of sharing common data processing utilities among all PyTorch domain libraries. I'll let you know if we have any other TorchGeo-specific feature requests, and I'll be closely following development of this library and porting of torchvision!

**Comment by ejguan** [comment]
We appreciate that you want to explore the option to load TorchGeo Dataset via `TorchData`.

From TorchData perspective, we would try our best to provide all fundamental utilities and modular DataPipes for users. So, like Kevin said, you can aggregate a few DataPipe as a single dispatch DataPipe to determine the data sources at the runtime for your custom need.

**Comment by adamjstewart** [comment]
Thanks, this should be what we're looking for! I'll try to play around with it when I get the chance. Thanks for the help!
