### ISSUE TITLE
osx-arm64 build missing from Anaconda pytorch channel

### ISSUE THREAD

**Issue by fotonick** [pytorch/data#676]
### 🐛 Describe the bug

Mac users on Apple silicon (M1, M2) cannot `conda install torchdata -c pytorch`, receiving "PackagesNotFoundError: The following packages are not available from current channels: -torchdata". This appears to be because torchdata was not built, packaged, and/or submitted to the pytorch channel. Is that something that can be done for future releases?

References:
* [torchdata](https://anaconda.org/pytorch/torchdata) shows only linux-64, osx-64, and win-64
* [torchtext](https://anaconda.org/pytorch/torchtext) for comparison, showing additional entries, including osx-arm64.

Many thanks.

### Versions

Any version.

**Comment by ejguan** [comment]
We are investigating how to provide such binaries to you as Github doesn't host m1 runner for us to create such packages.
As an intermediate solution, you can install `torchdata` by downloading from source and running `python setup.py install`.

**Comment by fotonick** [comment]
Thank you. I recognize that hardware access on CI is problematic. Lmk if you need a tester.

**Comment by jrgreene** [comment]
I was able to install torchdata on my M1 Max laptop using pip, but then when I tried to actually run the code I got this:

"_torchdata.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))"

I think this is the same issue as above as the root cause??? Basically, the binaries are not for the M1 chip.

Can I solve this issue by building from source as pointed out above?

**Comment by ejguan** [comment]
@jrgreene Yes, you can. And, if you want to enable AWSSDK as well. You can follow the instruction [here](https://github.com/pytorch/data/tree/main/torchdata/datapipes/iter/load#build-from-source) to compile torchdata from source. I have confirmed with AWS team that it can compiled on M1 chip. So, the C-extension for TorchData (used for AWSSDK) can be compiled for M1 machines.

**Comment by ejguan** [comment]
And, I am working on a PR to add m1 binary.

**Comment by ejguan** [comment]
@fotonick @jrgreene 
The nightly releases for arm64 are available on conda. You can install it via:
`conda install pytorch torchdata -c pytorch-nightly`
In the coming 0.4.1 torchdata release (this week or next week), we will provide arm64 releases as well.

**Comment by ejguan** [comment]
The binaries for arm64 becomes available for nightly release. You can get them via: `conda install pytorch torchdata -c pytorch-nightly`.

And, for the coming torchdata 0.4.1 minor releases (this week or the next week), you will be able to get arm64 build of torchdata using `conda install pytorch torchdata -c pytorch`.
