### ISSUE TITLE
Run tests from domains on our CI

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#69]
per title.
This would help us to notify domains about the BC breaking changes.

Reference:
- text: https://github.com/pytorch/text/blob/main/test/experimental/test_datasets.py
  - Run tests directly
- vision: https://github.com/pytorch/vision/tree/main/torchvision/prototype/datasets/_builtin
  - Call dataset creation to verify the API.
- audio: TODO
- torchrec: Wait until March when TorchRec is OSSed.

cc: @NivekT

**Comment by pmeier** [comment]
I'm currently adding tests for the `torchvision` datasets in pytorch/vision#4682. When this is merged, I'll update 

https://github.com/pytorch/data/blob/4802a350d1bf954d0785e0f22fd1fcde2deded76/.github/workflows/domain_ci.yml#L48-L49

to run them.

**Comment by ejguan** [comment]
@pmeier 
Thanks!

**Comment by ejguan** [comment]
Closing the issue as we have domain referencing the DataPipe utilization in vision/test/audio domains
