### ISSUE TITLE
DataLoader epoch size changes when setting `num_workers`>1

### ISSUE THREAD

**Issue by vedantroy** [pytorch/data#702]
### 🐛 Describe the bug

I wrote some code to read files in from a directory and do some processing (load them into tensors, etc. etc.)
However, I've noticed that when I set `num_workers` to be greater than 1, the size of the epoch scales proportionally.
So, for example, let's say with a batch size of 100, there are 5 batches in an epoch. When I increase the number of workers to 8, now there will be 40 batches in an epoch.

This happens with `DataLoader` or `DataLoader2`, or `dp.iter.FileLister`.

```python
import os
from types import SimpleNamespace

from tqdm import tqdm
import torchvision
import torchdata.datapipes as dp
from torch.utils.data import DataLoader,

def build_datapipes(root_dir, batch_size):
    datapipe = dp.iter.FSSpecFileLister(root_dir)
    # functional form of `dp.iter.Mapper`
    return datapipe.batch(batch_size)

if __name__ == "__main__":
    args = SimpleNamespace(in_dir="YOUR IN DIR", batch_size=100)
    datapipe = build_datapipes(args.in_dir, args.batch_size)
    # bug is here (try setting num_workers>1)
    dl = DataLoader(datapipe, batch_size=1, num_workers=1)

    _, _, files = next(os.walk(args.in_dir))
    total_files = len(files)

    for batch in tqdm(dl, total=total_files / args.batch_size):
        pass
```

### Versions

Collecting environment information...
PyTorch version: 1.12.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04 LTS (x86_64)
GCC version: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-41-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1080 Ti
Nvidia driver version: 515.48.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.1
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.12.0
[pip3] torch-optimizer==0.1.0
[pip3] torchdata==0.4.0
[pip3] torchmetrics==0.7.3
[pip3] torchvision==0.13.0
[conda] cudatoolkit               11.7.0              hd8887f6_10    conda-forge
[conda] numpy                     1.23.1                   pypi_0    pypi
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] torch                     1.12.0                   pypi_0    pypi
[conda] torch-optimizer           0.1.0                    pypi_0    pypi
[conda] torchdata                 0.4.0                    pypi_0    pypi
[conda] torchmetrics              0.7.3                    pypi_0    pypi
[conda] torchvision               0.13.0                   pypi_0    pypi

**Comment by ejguan** [comment]
Please take a look at our [tutorial](https://pytorch.org/data/beta/tutorial.html#working-with-dataloader). You might want to add `sharding_filter` in your pipeline to support dynamic sharding for multiprocessing.
