### ISSUE TITLE
"stable" releases are not available through PyTorch index

### ISSUE THREAD

**Issue by pmeier** [pytorch/data#731]
While `torchdata` is available on the [nightly](https://download.pytorch.org/whl/nightly/cpu) and [test](https://download.pytorch.org/whl/test/cpu) index, it is missing from the [stable](https://download.pytorch.org/whl/cpu) index. Is this intentional?

**Comment by ejguan** [comment]
Oh yeah. For stable releases, we rely on PyPI directly: https://pypi.org/project/torchdata/
