### ISSUE TITLE
Support file mask on list_files_by_s3 like list_files

### ISSUE THREAD

**Issue by ringohoffman** [pytorch/data#737]
### 🚀 The feature

Support a file mask on `list_files_by_s3` just like `list_files` does.

### Motivation, pitch

```python
dp.list_files_by_s3(masks="*.csv")
```

is nicer than

```python
dp.list_files_by_s3().filter(filter_fn=lambda filename: filename.endswith(".csv"))
```

**Comment by DongyuXu77** [comment]
Hope to work on it as a newbie

**Comment by DongyuXu77** [comment]
Does anyone work on it? If it isn't, I could take it

**Comment by ejguan** [comment]
> Does anyone work on it? If it isn't, I could take it

Feel free to open a PR
