### ISSUE TITLE
Allow `flatmap` to have no-op option which will vertically flatten datapipe

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/data#738]
```python
list(dp) # [[0,1,2],[3,4,5]]
dp = dp.flatmap()
list(dp) # [0,1,2,3,4,5]
```

This feels similar to `unbatch`, but should work with any iterable.

--

Looks like our final solution would be to allow `flatmap` to have no-op. 
Meanwhile, you can use:
```python
dp = dp.flatmap(fn = lambda x: x)
```

_Originally posted by @VitalyFedyunin in https://github.com/pytorch/data/issues/648#issuecomment-1217196626_

**Comment by mobikoz** [comment]
Happy to work on it as a newcomer.

**Comment by NivekT** [comment]
> Happy to work on it as a newcomer.

Great! I have assigned it to you and feel free to open a PR and let us know if you have any questions.
