### ISSUE TITLE
Import of `datasets` pollutes the global namespace

### ISSUE THREAD

**Issue by rehno-lindeque** [pytorch/data#751]
### 🐛 Describe the bug

In the huggingface iter datapipe a package called `datasets` is imported without any additional qualification.

If you happen to have your own `datasets` package then this will import it. This also causes a circular import if your `datasets` package happens to import `torchdata`. (This was not the case in torchdata `v0.3.0`)

See https://github.com/pytorch/data/blob/bb78231e5f87620385cb2f91cda87e7f9414eb4a/torchdata/datapipes/iter/load/huggingface.py#L13-L16

### Versions

```
Collecting environment information...
PyTorch version: 1.12.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: NixOS 22.05 (Quokka) (x86_64)
GCC version: (GCC) 11.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.34

Python version: 3.9.13 (main, May 17 2022, 14:19:07)  [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.18.16-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
Nvidia driver version: 515.48.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.941
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] torch==1.12.1+cu113
[pip3] torchdata==0.4.1
[pip3] torchvision==0.13.1+cu113
[conda] Could not collect
```

**Comment by ejguan** [comment]
First of all, it's fine to have circular import in Python as Python would cache the import result. And, `datasets` is a well-known package provided by huggingface and it's available across [PyPI](https://pypi.org/project/datasets/) and [conda](https://anaconda.org/conda-forge/datasets).

I am wondering whether it introduces any problem you. If so, could you please elaborate how it affects your work?

**Comment by rehno-lindeque** [comment]
> I am wondering whether it introduces any problem you. If so, could you please elaborate how it affects your work?

Sure, no problem. 

I don't use huggingface at all but I do have a subdirectory called `datasets`

```
── app
│   └── train
|         ├── __init__.py
│       ├── augmentations
|             └── __init__.py
│       ├── criterions
|             └── __init__.py
│       ├── datasets
|             └── __init__.py
│       ├── models
|             └── __init__.py
│       ├── preprocessors
|             └── __init__.py
```

Importing anything `torchdata.datapipes` from this subdirectory causes an error. (The circular import is a bit of red herring, it's more a case of the incorrect package being imported).

```
  File "..../app/train/datasets/....py", line 16, in Dataset
    s3_datapipe: datapipes.iter.IterDataPipe[
AttributeError: partially initialized module 'torchdata.datapipes' has no attribute 'iter' (most likely due to a circular import)
```

**Comment by ejguan** [comment]
Could you share a minimum repro example? I can't really reproduce the Error.

**Comment by rehno-lindeque** [comment]
I just wanted to mention I managed to fix this in my code repo by making sure that my `__main__.py` script was properly separated from my package. 

So that datasets would not be `./datasets` relative to the script, and would instead be `../app/train/datasets` relative to the script instead.

It's not my ideal directory structure, but in the end I think it's a python shortcoming rather than something to fix here.
