### ISSUE TITLE
`to_map_datapipe` doesn't behave lazily loading in multiprocessing

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#753]
### 🐛 Describe the bug

At this [line](https://github.com/pytorch/data/blob/719616a1b4791034da3d888357e3ef62c70806e3/torchdata/datapipes/iter/util/converter.py#L118-L119), when it's sent to child process, it will automatically load all data into memory. It leads to multiple problems:
- Data is not lazily loaded. It would take more time and more memory during the construction of multiprocessing
- The sharding is not going to be applied properly, as we are doing sharding after the worker processes are constructed.

Solution is straightforward. We should just remove it those lines from `to_map_datapipe`.

### Versions

main

**Comment by DongyuXu77** [comment]
I'd like to work on this as a newbie

**Comment by NivekT** [comment]
Hi @DongyuXu77,

Feel free to create a PR in `pytorch/pytorch` to fix that. It will need additional unit/integration tests to ensure that the converter behaves lazily in multiprocessing. There should be similar tests in `test_datapipe.py` or `test_dataloader.py` to guide you.

**Comment by DongyuXu77** [comment]
> Hi @DongyuXu77,
> 
> Feel free to create a PR in `pytorch/pytorch` to fix that. It will need additional unit/integration tests to ensure that the converter behaves lazily in multiprocessing. There should be similar tests in `test_datapipe.py` or `test_dataloader.py` to guide you.

OK, thank's a lot

**Comment by DongyuXu77** [comment]
I have read the comment carefully, and I need to double-check that the only thing I should do is remove the lines of code mentioned above and add a test unit? I can't figure out a way to get the correct self._map without worker_id in processes. 
@NivekT
