### ISSUE TITLE
Failing AIStore CI

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#778]
### 🐛 Describe the bug

See the example [log](https://github.com/pytorch/data/actions/runs/3068818736). The AIStore tests are failing on MacOS.
It seems that there is an undefined variable from `github.com/NVIDIA/aistore v0.0.0-20220915224653-1741e9446349`. @gaikwadabhishek  Do you know if there is a proper way to fix it? 

### Versions

main branch

**Comment by ejguan** [comment]
Closing as it seems the Error is automatically fixed after aistore's update

**Comment by gaikwadabhishek** [comment]
sorry for the late reply @ejguan. The team of AIStore took care of the issue. Thanks
