### ISSUE TITLE
Missing docstring of IterDataPipes in functional form

### ISSUE THREAD

**Issue by weiji14** [pytorch/data#792]
### 🐛 Describe the bug

When using an IterDataPipe in their functional form as recommended in https://pytorch.org/data/0.4/torchdata.datapipes.iter.html#torchdata.datapipes.iter.IterDataPipe, users have to write something like `dp.batch(...)`. However, when looking at the docstring or function signature, it doesn't show any of the possible keywords arguments such as `batch_size`, `drop_last`, etc, only some stuff about `functools.partial`.

Note: This issue was first reported at https://github.com/weiji14/zen3geo/issues/69. Here's a minimal working example using [`torchdata.datapipes.iter.Batcher`](https://pytorch.org/data/0.4/generated/torchdata.datapipes.iter.Batcher.html#torchdata.datapipes.iter.Batcher)

```python
import torchdata

dp = torchdata.datapipes.iter.IterableWrapper(iterable=["abc", "def"])
help(dp.batch)
```
produces

```python-traceback
Help on partial in module functools object:

class partial(builtins.object)
 |  partial(func, *args, **keywords) - new function with partial application
 |  of the given arguments and keywords.
 |  
 |  Methods defined here:
 |  
 |  __call__(self, /, *args, **kwargs)
 |      Call self as a function.
 |  
 |  __delattr__(self, name, /)
 |      Implement delattr(self, name).
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __reduce__(...)
 |      Helper for pickle.
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  __setattr__(self, name, value, /)
 |      Implement setattr(self, name, value).
 |  
 |  __setstate__(...)
 |  
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |  
 |  __class_getitem__(...) from builtins.type
 |      See PEP 585
 |  
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |  
 |  __vectorcalloffset__
 |  
 |  args
 |      tuple of arguments to future partial calls
 |  
 |  func
 |      function object to use in future partial calls
 |  
 |  keywords
 |      dictionary of keyword arguments to future partial calls
```

The expected behaviour is to have docstrings looking like that from `help(torchdata.datapipes.iter.Batcher)`:

```python-traceback
Help on class BatcherIterDataPipe in module torch.utils.data.datapipes.iter.grouping:

class BatcherIterDataPipe(torch.utils.data.datapipes.datapipe.IterDataPipe)
 |  BatcherIterDataPipe(datapipe: torch.utils.data.datapipes.datapipe.IterDataPipe, batch_size: int, drop_last: bool = False, wrapper_class=<class 'torch.utils.data.datapipes.datapipe.DataChunk'>) -> None
 |  
 |  Creates mini-batches of data (functional name: ``batch``). An outer dimension will be added as
 |  ``batch_size`` if ``drop_last`` is set to ``True``, or ``length % batch_size`` for the
 |  last batch if ``drop_last`` is set to ``False``.
 |  
 |  Args:
 |      datapipe: Iterable DataPipe being batched
 |      batch_size: The size of each batch
 |      drop_last: Option to drop the last batch if it's not full
 |      wrapper_class: wrapper to apply onto each batch (type ``List``) before yielding,
 |          defaults to ``DataChunk``
 |  
 |  Example:
 |      >>> from torchdata.datapipes.iter import IterableWrapper
 |      >>> dp = IterableWrapper(range(10))
 |      >>> dp = dp.batch(batch_size=3, drop_last=True)
 |      >>> list(dp)
 |      [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
 |  
...
```

Is there a way to modify the `@functional_datapipe` decorator code at https://github.com/pytorch/pytorch/blob/664058fa83f1d8eede5d66418abff6e20bd76ca8/torch/utils/data/datapipes/_decorator.py#L11-L38 to include the docstring? I think [`functools.wraps`](https://docs.python.org/3/library/functools.html#functools.wraps) is able to do it for Python functions, but not sure how this would work with Python classes.

### Versions

```
PyTorch version: 1.12.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0] (64-bit runtime)
Python platform: Linux-5.17.0-1017-oem-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] torch==1.12.0
[pip3] torchdata==0.4.0
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] torch                     1.12.0                   pypi_0    pypi
[conda] torchdata                 0.4.0                    pypi_0    pypi
```

**Comment by ejguan** [comment]
> Is there a way to modify the `@functional_datapipe` decorator code at https://github.com/pytorch/pytorch/blob/664058fa83f1d8eede5d66418abff6e20bd76ca8/torch/utils/data/datapipes/_decorator.py#L11-L38 to include the docstring? I think [`functools.wraps`](https://docs.python.org/3/library/functools.html#functools.wraps) is able to do it for Python functions, but not sure how this would work with Python classes.

@weiji14 Wondering have you tried to use `functools.wraps` to see if this works or not?

**Comment by weiji14** [comment]
> @weiji14 Wondering have you tried to use `functools.wraps` to see if this works or not?

No, `functools.wraps` won't work because 1) it's only for wrapping Python functions, but IterDataPipe is a class, and 2) It gets circular if we try to wrap the class as it is being defined...

A bit of searching led me to https://stackoverflow.com/questions/6394511/python-functools-wraps-equivalent-for-classes, but it looks a bit complicated :sweat_smile:

**Comment by severinsch** [comment]
This could be fixed by calling `functools.update_wrapper` after the relevant calls to `functools.partial` to update the `__doc__` of the created partial function.

The relevant `partial` calls for the `@functional_datapipe` decorator are [here](https://github.com/pytorch/pytorch/blob/664058fa83f1d8eede5d66418abff6e20bd76ca8/torch/utils/data/datapipes/datapipe.py#L120), [here](https://github.com/pytorch/pytorch/blob/664058fa83f1d8eede5d66418abff6e20bd76ca8/torch/utils/data/datapipes/datapipe.py#L143), [here](https://github.com/pytorch/pytorch/blob/664058fa83f1d8eede5d66418abff6e20bd76ca8/torch/utils/data/datapipes/datapipe.py#L246) and [here](https://github.com/pytorch/pytorch/blob/664058fa83f1d8eede5d66418abff6e20bd76ca8/torch/utils/data/datapipes/datapipe.py#L264).

[This commit](https://github.com/pytorch/pytorch/commit/b98751b34d677548a2fab7b985b4b76692d540be) in my [fork](https://github.com/severinsch/pytorch) of [pytorch/pytorch](https://github.com/pytorch/pytorch) includes a fix to this issue and makes the mentioned example work as expected.

Should I open a PR for pytorch/pytorch, even though the issue is in pytorch/data?

**Comment by weiji14** [comment]
> Should I open a PR for pytorch/pytorch, even though the issue is in pytorch/data?

Yes please! It doesn't look like the fix can be easily applied in https://github.com/pytorch/data, so best to patch things upstream at https://github.com/pytorch/pytorch. Could you open the PR and link to this issue for context? Thanks :pray:

**Comment by ejguan** [comment]
> Should I open a PR for pytorch/pytorch, even though the issue is in pytorch/data?

Yes, please. That would be great.

**Comment by weiji14** [comment]
Should have been fixed in https://github.com/pytorch/pytorch/pull/100503 and https://github.com/pytorch/pytorch/pull/100446 (thanks @NivekT and @ejguan for the reviews!). This will be out in Pytorch 2.1 hopefully :crossed_fingers:

For those that can't wait, the Pytorch nightly builds installed via `pip install --pre torch torchdata --index-url https://download.pytorch.org/whl/nightly/cu121` does contain the bugfix. On `torch=2.1.0.dev20230519+cu121` and `torchdata=0.7.0.dev20230519`, I've confirmed that `help(dp.batch)` shows a better docstring like:

```
Help on partial in module torch.utils.data.datapipes.iter.grouping:

functools.partial(functools.partial(<function It...rDataPipe'>, False), IterableWrapperIterDataPipe)
    Creates mini-batches of data (functional name: ``batch``). An outer dimension will be added as
    ``batch_size`` if ``drop_last`` is set to ``True``, or ``length % batch_size`` for the
    last batch if ``drop_last`` is set to ``False``.
    
    Args:
        datapipe: Iterable DataPipe being batched
        batch_size: The size of each batch
        drop_last: Option to drop the last batch if it's not full
        wrapper_class: wrapper to apply onto each batch (type ``List``) before yielding,
            defaults to ``DataChunk``
    
    Example:
        >>> # xdoctest: +SKIP
        >>> from torchdata.datapipes.iter import IterableWrapper
        >>> dp = IterableWrapper(range(10))
        >>> dp = dp.batch(batch_size=3, drop_last=True)
        >>> list(dp)
        [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
```

Closing as done :tada:
