### ISSUE TITLE
The Sampler datapipe produces indices instead of the actual data.

### ISSUE THREAD

**Issue by philip-bl** [pytorch/data#796]
### 🐛 Describe the bug

```
from torchdata.datapipes.iter import Sampler, IterableWrapper
from torch.utils.data import RandomSampler

print(tuple(Sampler(
    IterableWrapper(range(1000, 1100)),
    RandomSampler,
    sampler_kwargs={"num_samples": 3})))
```

produces three numbers from the 0..99 range, e.g. `(11, 27, 15)`, but I expect it to produce three numbers from the 1000..1099 range.

### Versions

torchdata 0.4.1

**Comment by ejguan** [comment]
This is the expected behavior of `Sampler`.
And, for `IterDataPipe`, since there is no random-accessing pattern. To get sample data, you should do:
```
dp = IterableWrapper().shuffle().head(3)
print(tuple(dp))
```
