### ISSUE TITLE
Create .pyi files for DataPipes

### ISSUE THREAD

**Issue by NivekT** [pytorch/data#80]
## 🚀 Feature

Create .pyi files for DataPipes to provide information for IDEs

As @ejguan mentioned, codegen is needed in order for all the comments and argument types to be automatically attached to the .pyi file. We also need to account for the fact that operations exist in both Core and TorchData.

## Motivation

These files will allow IDEs to provide more information to users when they are using DataPipes, and will enable features such as code autocompletion.

cc: @VitalyFedyunin @ejguan

**Comment by NivekT** [comment]
This is done with https://github.com/pytorch/data/pull/224, but we still need to automate the process.

**Comment by ejguan** [comment]
Can we close this issue?

**Comment by NivekT** [comment]
Yes
