### ISSUE TITLE
`import torchdata`: `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by rsokl** [pytorch/data#844]
### 🐛 Describe the bug

OS: Ubuntu 18.04.6 LTS

```
conda create -n torchdata python=3.9 -c conda-forge
conda activate torchdata
conda install pytorch torchdata cpuonly  -c pytorch
```

When I attempt to run

```python
import torchdata
```

I get:

```
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/ry26099/miniconda3/envs/torchdata/lib/python3.9/site-packages/torchdata/_torchdata.so)
```

### Versions

```
[pip3] torch==1.12.1
[pip3] torchdata==0.4.1
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   2.0                           0    pytorch
[conda] mkl                       2022.1.0           hc2b9512_224  
[conda] pytorch                   1.12.1              py3.9_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchdata                 0.4.1                      py39    pytorch
```

**Comment by NivekT** [comment]
I think you need to install/update the C compiler (for example, `gcc`). Is it possible for you to do that?

cc: @ejguan

**Comment by rsokl** [comment]
I don't think it is possible on 18.04.6

**Comment by ejguan** [comment]
Try `pip install torchdata` as well. We do have manylinux2014 which should provide minimum `GLIBC_2.27`

**Comment by rsokl** [comment]
Thanks! Mainly just wanted to let you know about this as a potential issue with the current conda recipe for Ubuntu 18

**Comment by ejguan** [comment]
I am reopening this issue since it seems we might have a working solution. I need to find a proper container to build conda package that is backward compatible with GLIBC_2.27.

**Comment by ejguan** [comment]
@rsokl Hey, I just enable the conda release with lower glibc requirement. Do you mind helping me verify it by installing our new nightly release?
you can do `conda install torch torchdata -c pytorch-nightly`

**Comment by Qjbtiger** [comment]
Thanks, work for me while my system is Ubuntu 18.04.4

**Comment by rsokl** [comment]
@ejguan I ended up upgrading my Ubuntu before I saw this update. Thank you for enabling the new conda release! It sounds like it is working for @Qjbtiger
