### ISSUE TITLE
MaxTokenBucktizer for dict type item

### ISSUE THREAD

**Issue by Lingeng56** [pytorch/data#881]
### MaxTokenBucktizer For Dict Type Item

I build a dataset which type of items is a python dictionary, and when I try to use MaxTokenBucktizer, I got an error
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/78547692/199952414-7f992007-740f-402a-9d9b-15cf64ecce75.png">
And I check the source code of torchdata, it caused by heappush method which not support python dict.
<img width="812" alt="image" src="https://user-images.githubusercontent.com/78547692/199951894-803a1908-f771-4b29-a1d2-77eb43d88aa2.png">

Could another data structures be used without affecting performance to store buffer data?  I think it's very common to use dictionary as item type..

### Versions

pytorch 1.12.1
torchdata 0.4.1

**Comment by Lingeng56** [comment]
Maybe it's because my code is wrong
<img width="963" alt="image" src="https://user-images.githubusercontent.com/78547692/199954671-b067fc27-5f0e-434a-ba8e-dee18ef5a9d2.png">
above is my code
`self.sampler` is an instance of `torch.utils.data.DistributedSampler`

**Comment by ejguan** [comment]
Thanks for finding this problem as `dict` is not comparable in `heapq`. I can send a patch to fix this problem.

**Comment by Lingeng56** [comment]
> Thanks for finding this problem as `dict` is not comparable in `heapq`. I can send a patch to fix this problem.

Hi, due to some version problems, I'd like to implement MaxTokenBucktizer from scratch, but with my implemantation, cuda cache allocated is continuely increasing due to dynamic batch size, which caused an oom error. I think it was caused by pytorch cache machnism, but I dont know how to solve it... Did you ever meet any similar problems ? Or maybe you have an idea to solve this problem.❤️

**Comment by ejguan** [comment]
@Lingeng56 

It would be good for us to have a minimum repro script, otherwise it's hard to say. I would assume an explicit `del` of buffer would help.

**Comment by ejguan** [comment]
@Lingeng56 
It's weird as I can't tell your code is using cuda tensor

**Comment by Lingeng56** [comment]
> @Lingeng56 It's weird as I can't tell your code is using cuda tensor

My data will convert to cuda tensor during collation in dataLoader..And Sampler contains index of each data item, so you can't see any code about cuda tensor in my screenshot.
My problem is cuda memory allocated will continually increasing during training procedure because of dynamic batch size. I think this caused by pytorch's cache mechanism. Maybe you ever met similar problems or you know how to deal with this problem.
