### ISSUE TITLE
Steps per epoch for training 

### ISSUE THREAD

**Issue by netw0rkf10w** [pytorch/data#884]
### 🚀 The feature

For huge datasets, an epoch may take a very long time to complete and it's good practice to perform evaluation and model checkpointing every N steps instead of at the end of an epoch. The tricky part lies at resuming training: how to tell the data loader to start from where it was left off? It would be great if torchdata could provide such a feature. 

I have no idea how such a feature could be implemented, but from a user perspective, the interface would be best to resemble the common usage:

- A `dataloader.state_dict()` method that returns necessary information on where the data loading was left off.
- A `dataloader.load_state_dict(saved_state_dict)` method for loading the saved state_dict.

### Motivation, pitch

See above.

**Comment by ejguan** [comment]
We do have this feature in our mind during the development of `DataLoader2`.
See:
https://github.com/pytorch/data/blob/b1b3406389fa6665ec3422ae5e1ebf65ae7e2938/torchdata/dataloader2/dataloader2.py#L219

Please stay tuned as this feature hasn't been accomplished yet.

**Comment by netw0rkf10w** [comment]
Ah that is great! Thanks for the quick reply. I look forward to testing it at release!

**Comment by netw0rkf10w** [comment]
@ejguan I have a quick question please. I had a quick look at the current implementation and it's more complicated than I thought. I don't know much about dataloader2 so this question may sound stupid: Wouldn't it be suffice to store the indices of the already consumed training examples (or alternatively the remaining ones)?

**Comment by ejguan** [comment]
There won't be the concept of indices in `DataPipe` + `DataLoader2` regime because we are targeting streaming scenario where the number of data (indices) is unknown to us.

**Comment by ejguan** [comment]
For hacking purpose, you might be able to add a wrapper around the existing `DataLoader` by simply storing the sampler state.

**Comment by netw0rkf10w** [comment]
> There won't be the concept of indices in `DataPipe` + `DataLoader2` regime because we are targeting streaming scenario where the number of data (indices) is unknown to us.

Ah I see. That makes sense. Thanks.

> For hacking purpose, you might be able to add a wrapper around the existing `DataLoader` by simply storing the sampler state.

Indeed, I was about to implement something like that. It's a bit tricker to implement for training with DDP though. I noticed that @VitalyFedyunin attempted to implement this (https://github.com/pytorch/pytorch/issues/36650#issuecomment-1144149178_) but did not come up with a satisfactory results, so maybe it's tricker than I thought.
