### ISSUE TITLE
Protecting users from overwriting special DataPipe methods

### ISSUE THREAD

**Issue by NivekT** [pytorch/data#886]
### 🚀 The feature

There are some built-in methods that exist across DataPipes (most commonly `reset`, and potentially `full_stop`, `resume` in the near future). Those methods are often used in ways that are hidden/not obvious to the users. Notably, `reset` is called when `iter(datapipe)` is called.

Currently, it is possible to define a new custom DataPipe with attributes using those names. While we cannot completely prohibit that, we should consider to rename those methods to different names (e.g. `_reset` or `__reset`) to decrease the probability of accidental overwrites of those names. Suggestions are welcomed

### Motivation, pitch

Protect users from overwriting special DataPipe methods

### Alternatives

Suggestions are welcomed

**Comment by ejguan** [comment]
You can add a `final` decorator to the `_reset` method to prevent overriding.
https://peps.python.org/pep-0591/

But, I am not sure about if it would prevent users to override the method by an attributed with the same name

**Comment by thomasdick** [comment]
@MrToaster1 and myself had a look at this issue.

Our suggestion is to add the @final annotation, such that mypy throws a soft hint when you overwrite the method, see mypy documentation https://mypy.readthedocs.io/en/stable/final_attrs.html#final-methods.
We tried this for the reset and resume methods of all datapipes we could find, see PR: https://github.com/pytorch/data/pull/1076

As for renaming the methods, we are not sure if they are already used outside the affected datapipe classes. Renaming them might cause additional effort to rework existing code?

**Comment by ejguan** [comment]
@thomasdick Thanks, responded to your PR directly
