### ISSUE TITLE
`IoPathFileLoader` should default mode to the same value as `FileLoader`

### ISSUE THREAD

**Issue by fmassa** [pytorch/data#90]
## 🚀 Feature

Self-explanatory. I believe the modes should be the same for ease of exchangeability.
PyTorch [`FileLoader` uses `b` by default](https://github.com/pytorch/pytorch/blob/62feadd76fb5760faccd526d9064b9ba5de13083/torch/utils/data/datapipes/iter/fileloader.py#L30), while `IoPathFileLoader` uses `r` https://github.com/pytorch/data/blob/4802a350d1bf954d0785e0f22fd1fcde2deded76/torchdata/datapipes/iter/load/iopath.py#L56

**Comment by ejguan** [comment]
@NivekT Is this issue has been solved in one of your PRs? Can we close it?

**Comment by NivekT** [comment]
Yep, fixed by https://github.com/pytorch/pytorch/pull/70367.
