### ISSUE TITLE
Use iopath in `SaverIterDataPipe`

### ISSUE THREAD

**Issue by fmassa** [pytorch/data#91]
## 🚀 Feature

`iopath` provides an API that can replace `open` and support saving to multiple destinations (including S3), we should probably reimplement `SaverIterDataPipe` to rely on `iopath` instead.

We could even then rename the functional API so that it's called `save` instead of `save_to_disk`.

**Comment by ejguan** [comment]
Understood. I will go over `iopath` today and figure out a way to align everything to `iopath`.
