### ISSUE TITLE
`DistributedReadingService` supports multi-processing reading

### ISSUE THREAD

**Issue by xiaosu-zhu** [pytorch/data#911]
### 🚀 The feature

`TorchData` is a great work for better data loading! I have tried it and it gives me a nice workflow with tidy code-style.❤️

When using DDP, I work with the `DataLoader2` where `reading_service=DistributedReadingService()`. I find this service runs one worker for outputting datas per node. This means it has lower reading throughput than the legacy `DataLoader`, which utilizes multiple workers with the total worker number = `num_workers * world_size`.

Therefore, is it possible to combine `DistributedReadingService` with multi-processing reading? This could be possibly done by introducing `PrototypeMultiProcessingReadingService` into  `DistributedReadingService` (Just guessing. I'm not a pro for handling this.).

### Motivation, pitch

I think this feature could be a part of #427 . The detailed motivation is declared above.

**Comment by ejguan** [comment]
Thank you for exploring `TorchData`. We are working on something called `SequentialReadingService` to combine both `DistributedReadingService` + `MultiprocessingReadingService`.

As a workaround, I temporarily added all distributed features to `PrototypeMultiProcessingReadingService` except attaching `fullsync` operation to the pipeline. So, for now, you can achieve dist + mp as:
```py
dp = dp.fullsync()  # Attach FullSync to the original pipeline
rs = PrototypeMultiProcessingReadingService(...)
dl = DataLoader2(dp, reading_service=rs)
```

**Comment by ejguan** [comment]
> The only drawback is that the reading service will **drop last batch** if the number of batches are not divisible by world size.

This is exactly what `fullsync` is doing here to make sure distributed dataset sharing the same length.

> Notably, it seems @ejguan solution will get stuck forever in this case if you use any operation requires sync during training.

As I said in my answer, a `fullsync` is required after `sharding_filter()`.

**Comment by K-Nick** [comment]
> > The only drawback is that the reading service will **drop last batch** if the number of batches are not divisible by world size.
> 
> This is exactly what `fullsync` is doing here to make sure distributed dataset sharing the same length.
> 
> > Notably, it seems @ejguan solution will get stuck forever in this case if you use any operation requires sync during training.
> 
> As I said in my answer, a `fullsync` is required after `sharding_filter()`.

 I ignored this feature before. Thx!

**Comment by wangers** [comment]
> Another option is to wrap datapipe with dataloader v1 yourself based on `DistributedReadingService`. This works for me so far.
> 
> ```python
>     def initialize(self, datapipe: DataPipe) -> DataPipe:
>         ....
>         # Only append FullSyncIterDataPipe if it's not presented at the end of the pipeline
>         if not isinstance(datapipe, FullSync):
>             datapipe = datapipe.fullsync(self._timeout)
> 
>         dataloader = DataLoader(datapipe, **self._multiproc_args)
> 
>         self._datapipe = IterableWrapper(dataloader)
>         return datapipe
> ```
When wrap with v1 dl, the main process spawn num_workers datapipe. In this case, the fullsync can't construct a gloo group(dist.new_groups(backend="gloo"), which aims to reduce the end state of datapiplines. Do you encounter the same propblem?

**Comment by ejguan** [comment]
Small update:
With https://github.com/pytorch/data/pull/950, `fullsync` DataPipe will remain in the main process. For any custom DataPipe that needs to be placed in the main process, you can add `is_replicable` method and returning `False` to the custom DataPipe class

**Comment by xiaosu-zhu** [comment]
Thanks for your hard work! @ejguan 👍
