### ISSUE TITLE
Start to graduate `PrototypeMultiProcessingReadingService` from "prototype mode" 

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#932]
unrelated: we should start to graduate it from "prototype mode" and starts find initial pioneering use case adoption~

_Originally posted by @wenleix in https://github.com/pytorch/data/pull/919#discussion_r1055161856_

**Comment by ejguan** [comment]
We should start to replace `MultiprocessingReadingService` by `PrototypeMultiProcessingReadingService`

**Comment by NivekT** [comment]
Agree, and we need rigorously testing for this. Last I checked `PrototypeMultiProcessingReadingService` seems to behave correctly when things go right, but I worry that it doesn't necessarily clean up properly when an exception is raised.

**Comment by ejguan** [comment]
Forget to mention, currently `PrototypeMultiProcessingReadingService` has distributed code, we need to graduate when the `SequentialRS` becomes available to combine both `PrototypeMultiProcessingReadingService` and `DistributedReadingService`.

**Comment by wenleix** [comment]
> Forget to mention, currently PrototypeMultiProcessingReadingService has distributed code, the graduation is blocked by availability of SequentialRS to combine both PrototypeMultiProcessingReadingService and DistributedReadingService. Then, the distributed code from PrototypeMultiProcessingReadingService can be removed.

With #985, what's leaving to graduate Prototype? :)

**Comment by ejguan** [comment]
> With #985, what's left to graduate Prototype? :)

Nothing in my mind. We can start to change it next week.
