### ISSUE TITLE
Make portalocker optional to guarantee minimum dependency

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#940]
### 🚀 The feature

This was a concern raised earlier in https://github.com/pytorch/data/issues/441
When users don't need to use the on-disk cache, they don't necessarily need to handle the installation of `portalocker`, especially for windows users.

### Motivation, pitch

Make TorchData more easy to install

**Comment by NivekT** [comment]
That makes sense to me

**Comment by ejguan** [comment]
Adding this to milestone 0.6

**Comment by ejguan** [comment]
Another thing needs to be considered is to make sure TorchText's CI is not broken after this change.
