### ISSUE TITLE
Full Support for HuggingFace-Datasets

### ISSUE THREAD

**Issue by SvenDS9** [pytorch/data#944]
### 🚀 The feature

Currently `HuggingFaceHubReaderIterDataPipe` is a wrapper for `load_dataset()` (https://huggingface.co/docs/datasets/v2.6.1/en/package_reference/loading_methods#datasets.load_dataset). `load_dataset()` however supports many more optional arguments. 
If we want to fully support downloading from HuggingFace we need to add these options to `HuggingFaceHubReaderIterDataPipe` as well.

### Motivation, pitch

E.g.  the [oscar](https://huggingface.co/datasets/oscar)-dataset requires you to also provide a name, which is not possible when using `HuggingFaceHubReaderIterDataPipe`.

I could provide a fix for this.

**Comment by ejguan** [comment]
Thanks for raising this feature request. We would love to accept any PR to fix that.
