### ISSUE TITLE
Broken tests due to upgrade of `fsspec`

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#956]
### 🐛 Describe the bug

After `fsspec` is updated `2023.1.0` from `2022.11.0 `, this [test](https://github.com/pytorch/data/blob/38e0d03454a9018cb7ebf76e6b31379db913f8a1/test/test_fsspec.py#L177) becomes broken due to `AttributeError: 'dict' object has no attribute 'startswith'`

Example failed workflow: https://github.com/pytorch/data/actions/runs/3969171216/jobs/6803298832

### Versions

main branch

**Comment by NivekT** [comment]
I have identified the issue. In the old version, the default argument is `details=False` for method `ls`, thus it returned a list of `str`. In the new version, the default is `details=True`, which returns list of `dict`.

Source code:
https://github.com/fsspec/filesystem_spec/blob/2023.1.0/fsspec/implementations/memory.py#L34

I will open a PR to fix soon.

**Comment by ejguan** [comment]
Thank you!
