### ISSUE TITLE
Modify exception handling of online Datapipes

### ISSUE THREAD

**Issue by SvenDS9** [pytorch/data#963]
### 🚀 The feature

Add an optional argument to `HTTPReaderIterDataPipe `to specify error handling.

https://github.com/pytorch/data/blob/2ca1fa6483e58c6428319393e1aab4c26f576bec/torchdata/datapipes/iter/load/online.py#L89-L94
`_get_response_from_http()` raises an exception if an error occurs. 

### Motivation, pitch

While working with `HTTPReaderIterDataPipe` I have noticed that failing HTTP-requests are not handled gracefully. This means that the DataPipe cannot be continued after an error occurs. Therefore I propose to add an optional argument which allows the user to continue the datapipe with the next url in case of an error.

### Alternatives

See https://discuss.pytorch.org/t/exception-handling-when-using-datapipes/170959

### Additional context

This also affects the other Datapipes in online.py which read from remote. It would probably make sense to add this feature there as well.

**Comment by NivekT** [comment]
This seems like a reasonable proposal. I think we should raise a warning at the minimum if an URL fails.

I also wonder if we can provide an option to retry or try an alternative (this might make the scope too big so feel free to ignore).

**Comment by SvenDS9** [comment]
Thanks!
I like the idea of the warning. I will implement this and for now will focus only on the continue option to keep the scope small. At a later point I mght add retry behavior.
The chances of success of retrying immediately are probably quite small...what do you think?
