### ISSUE TITLE
Fix tests for S3

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#984]
### 🐛 Describe the bug

S3 test is broken due to the the datasets have been updated in the public bucket, which we don't have any control.
Test case:
https://github.com/pytorch/data/blob/807db8f8c7282b2f48b48b1e07439c119a2ba12f/test/test_remote_io.py#L256-L291

And, we previously just fix the test by updating the number of files per bucket whenever the dataset update happened. It's not a long-term solution to maintain CI. To fix it, we might choose from the following solutions:
- Only validate some files existing in the output, not the total file count from each bucket
- Use mock to simulate the result
- Add our own stable bucket for testing

I prefer the first solution for two reasons:
- We want to test the functionality provided by `_torchdata.so`. Even though mocking the result of this extension would guarantee test green, it doesn't really cover the test over the extension.
- The third option might work but it also means our own bucket will be exposed on Github, which is not ideal IMHO.

### Versions

main

**Comment by ShiboXing** [comment]
Hi everyone, I'm also investigating this issue. 
What do you feel about a solution installing aws-cli at test time, and then verifying the s3 bucket files through the cli. 
Something like 
    `        
    res = subprocess.run("aws s3 ls --no-sign-request s3://ai2-public-datasets/ --recursive", shell=True, check=True, capture_output=True)
    num_items =  len(res.stdout.decode("utf-8").split("\n")) - 1
`
with `awscli` added in the requirements.txt

**Comment by ejguan** [comment]
@ShiboXing Yeah, that would be ideal solution. Thanks!

**Comment by ShiboXing** [comment]
awesome, will attach the PR soon!

**Comment by ShiboXing** [comment]
here is the PR: https://github.com/pytorch/data/pull/997

**Comment by ShiboXing** [comment]
Hi team, do you mind helping me out with the workflows that need approvals?
I also got a torchvision failure on all platform that I'm not sure how to fix.

**Comment by ShiboXing** [comment]
Hi team, thanks for the help. 
Just addressed the reviews in the PR and need checks approval again (posting here in case PR doesn't notify)

**Comment by ShiboXing** [comment]
Hi team, please let me know what changes I should make, if any. The pipeline just finished executing. Thanks!
