### ISSUE TITLE
README documentation links not working

### ISSUE THREAD

**Issue by SvenDS9** [pytorch/data#993]
### 📚 The doc issue

Some links in the README do not work.
The link to the tutorial doesn't work, it currently points to
https://pytorch.org/data/main/tutorial.html -> 404
This concerns the tutorial section and two questions in the FAQ ("What should I do if the existing set of DataPipes does not do what I need?"  and "How is multiprocessing handled with DataPipes?" )

### Suggest a potential alternative/fix

The correct link is probably:
https://pytorch.org/data/beta/tutorial.html

**Comment by ejguan** [comment]
Thanks for reporting it. After #980 is landed, the url paths have been changed.
The actualy link should be: https://pytorch.org/data/main/dp_tutorial.html

If you want, please feel free to open a PR to fix it.

**Comment by SvenDS9** [comment]
Will do
