### ISSUE TITLE
PyTorch 1.14 support

### ISSUE THREAD

**Issue by kimihailv** [pytorch/data#999]
### 🚀 The feature

Support of PyTorch 1.14

### Motivation, pitch

Latest version of TorchData requires PyTorch 1.13 as dependency. It is inconvenient if PyTorch 1.14 has been already installed

**Comment by ejguan** [comment]
I am not aware of PyTorch is going to have 1.14 releases. The current nightly releases have been bumped to 2.0.

If you want to install nightly releases for pytorch (2.0) and torchdata (0.6), you can do:
- PyTorch: `pip3 install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu`
- TorchData: `pip3 install --pre torchdata --extra-index-url https://download.pytorch.org/whl/nightly/cpu`

**Comment by kimihailv** [comment]
Thanks
